### ISSUE TITLE
Image for Spark 3.3 with Scala version 2.13

### ISSUE THREAD

**Issue by datapanda91** [bitnami/containers#10070]
### Name and Version

bitnami/spark

### What is the problem this feature will solve?

I would like to use Spark distribution pre-built with Scala 2.13. Currently all tags seem to only provide Scala 2.12.

### What is the feature you are proposing to solve the problem?

A new image tag with Spark built for Scala 2.13.

**Comment by carrodher** [comment]
Thanks for the suggestion, at this moment we are downloading the source code from https://spark.apache.org/downloads.html. In that page there is a note about the Scala version used:
> Note that Spark 3 is pre-built with Scala 2.12 in general and Spark 3.2+ provides additional pre-built distribution with Scala 2.13.

In that sense, since we are just releasing one flavor of Spark, we opted for using the default/generic package, which is the one built with Scala 2.12. If there is a change regarding this topic coming from the upstream maintainers, we will adapt our release pipeline; but for now, it seems the default version is 2.12.
