### ISSUE TITLE
[bitnami/wordpress-nginx] Permission denied on wp-content folder when mapping plugins and themes subfolders

### ISSUE THREAD

**Issue by ziodave** [bitnami/containers#1050]
### Name and Version

bitnami/wordpress-nginx:6

### What steps will reproduce the bug?

1. Create a docker-compose and map the `wp-content/plugins` and `wp-content/themes` folders
2. Run `docker compose up`
3. The set-up will fail with the following errors:

```
cp: cannot create regular file '/bitnami/wordpress/wp-content/index.php': Permission denied
cp: cannot create directory '/bitnami/wordpress/wp-content/languages': Permission denied
cp: cannot create directory '/bitnami/wordpress/wp-content/upgrade': Permission denied
cp: cannot create directory '/bitnami/wordpress/wp-content/uploads': Permission denied
```

### What is the expected behavior?

Expected behavior is for the installation to work and complete successfully

### What do you see instead?

```
cp: cannot create regular file '/bitnami/wordpress/wp-content/index.php': Permission denied
cp: cannot create directory '/bitnami/wordpress/wp-content/languages': Permission denied
cp: cannot create directory '/bitnami/wordpress/wp-content/upgrade': Permission denied
cp: cannot create directory '/bitnami/wordpress/wp-content/uploads': Permission denied
```

### Additional information

The mapped volumes are owned by `root`:

```
drwxr-xr-x 4 root root 4096 Jun 27 11:02 wp-content
```

**Comment by fmulero** [comment]
We are going to transfer this issue to `bitnami/containers`. 

In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`.

Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues

**Comment by siddjellali** [comment]
up

**Comment by itay-sho** [comment]
up
