### ISSUE TITLE
[bitnami/kubectl] Missing curl and wget

### ISSUE THREAD

**Issue by rubyalwaystaken** [bitnami/containers#11367]
### Name and Version

bitnami/kubectl:1.22.15

### What steps will reproduce the bug?

1. Run `docker run --rm -it --entrypoint /bin/sh bitnami/kubectl:1.24`
2. Run `curl` or `wget`

This leads to a "command not found" message. 
`apt list --installed` does not list wget and curl either.

Doing the same on a 2 months older version (1.25.0) does not reproduce this issue. 

### What is the expected behavior?

curl and wget should be installed and usable

### What do you see instead?

"command not found" when calling the aforementioned missing packages

**Comment by carrodher** [comment]
Hi, we have been working on removing non-needed dependencies to have more secure containers, reducing the attack surface and the container size. `curl` is not needed in those container images you’re mentioning, that’s why it was removed from the container.

You can use the `install_packages` script to install it if it is needed for your use case when creating your custom image based on Bitnami’s or using `curl` as part of any custom script.
Please take into account, Bitnami containers are non-root by default, in order to be able to install packages you will need to run the container as root (at least when installing the package)
