### ISSUE TITLE
Critical vulnerabilities in OpenSSL component

### ISSUE THREAD

**Issue by mulder999** [bitnami/containers#12461]
### Name and Version

bitnami/keycloak:19

### What steps will reproduce the bug?

Scanning latest docker container image with [Dependency Track SaaS](https://yoursky.blue/dependency-track-saas/) shows that the component `OpenSSL1.1.1n-0+deb11u3` suffers from 3 vulnerabilities:
- CVE-2022-1292 (critical)
- CVE-2022-2068 (critical)
- CVE-2022-2097 (medium)

### What is the expected behavior?

Update to latest version of OpenSSL, which includes all the fixes namely [OpenSSL_1_1_1s](https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_1s) as of today

### What do you see instead?

![KeyCloakVulnerabilitiesExploitable](https://user-images.githubusercontent.com/1905023/199752374-745d4efd-a2b6-400d-997a-9ef731ee198a.JPG)

**Comment by carrodher** [comment]
Hi, unfortunately, those security vulnerabilities are not fixed by the OS or the application itself, so although we built the images on a regular basis to provide the latest version of system packages, this kind of CVE will be reported while there is no new version patching the issue in the OS or the application.

The Bitnami Application Catalog (OpenSource) is based on Debian 11 but Bitnami, as part of VMware, provides a custom container and Helm Charts catalog based on the desired base image (generic distro such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04, 20.04 & 22.04, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

**Comment by mulder999** [comment]
Hi @carrodher, I am not sure to get to your point.

Within several bitnami images (keycloak, nginx, mariadb, postgresQL-repmgr, ...) there is a vulnerable openssl executable. I am unsure why it is even included in the first place but a new release of this executable is available which fixes the vulnerabilities. Hence I would expect to eventually see it in a future release of the container.

**Comment by carrodher** [comment]
The Bitnami containers use an underlying distro (Debian 11 in this case), we install all the packages from the distro repositories. It is possible that the executable is released from the upstream project (its maintainers) but it is not included in the package repositories.
Once the package present in the distro repositories is updated, our automatic test & release pipeline will release a new revision of the Bitnami containers bundling the latest available versions of the system packages

**Comment by mulder999** [comment]
@carrodher thanks for clarification will report vulnerabilities to openssl Debian package's maintainer
