### ISSUE TITLE
Spark 3.3.1 with Scala 2.13 with Bitnami Docker Image

### ISSUE THREAD

**Issue by ardesai** [bitnami/containers#13248]
### Name and Version

bitnami/spark

### What is the problem this feature will solve?

I would like to use Bitnami Docker image with [Spark 3.3.1 with Scala 2.13](https://www.apache.org/dyn/closer.lua/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3-scala2.13.tgz).
Looking at the available images, I can't find the one with Scala 2.13:
https://hub.docker.com/r/bitnami/spark
https://github.com/bitnami/containers/tree/main/bitnami/spark

### What is the feature you are proposing to solve the problem?

Have Spark 3.3.1 with Scala 2.13 base image.

### What alternatives have you considered?

Looking at the [DockerFile ](https://github.com/bitnami/containers/blob/main/bitnami/spark/3.3/debian-11/Dockerfile) with the latest version, uses package:
https://downloads.bitnami.com/files/stacksmith/spark-3.3.1-1-linux-amd64-debian-11.tar.gz

I guess spark-3.3.1-1-linux-amd64-debian-11.tar.gz seems to be the latest version and comes with Scala 2.12.
Do we have spark package with 3.3.1 with Scala 2.13?
If yes, then I will update the DockerFile and create a custom image for our requirements.

Can't seem to list the available packages on https://downloads.bitnami.com/files/stacksmith/

**Comment by carrodher** [comment]
Thanks for the suggestion, at this moment we are downloading the source code from https://spark.apache.org/downloads.html. On that page there is a note about the Scala version used:
> Note that Spark 3 is pre-built with Scala 2.12 in general and Spark 3.2+ provides additional pre-built distribution with Scala 2.13.

In that sense, since we are just releasing one flavor of Spark, we opted for using the default/generic package, which is the one built with Scala 2.12. If there is a change regarding this topic coming from the upstream maintainers, we will adapt our release pipeline; but for now, it seems the default version is 2.12.

**Comment by ardesai** [comment]
Thanks for the answer @carrodher 

On the page https://spark.apache.org/downloads.html, you have an option 'Choose a package type' with Scala 2.13, so the upstream maintainers are providing an option to package Scala 2.13 with the Spark.

**Comment by carrodher** [comment]
Yes, there is an option for downloading a version with a different bundled Scala, but in this case since we are just publishing a single version, we opt for following the default approach which is using scala 2.12 according to 
> Note that Spark 3 is pre-built with Scala 2.12 in general and Spark 3.2+ provides additional pre-built distribution with Scala 2.13.

**Comment by ardesai** [comment]
We would like to use [Spark Helm Chart from Bitnami](https://github.com/bitnami/charts/tree/main/bitnami/spark) and our application uses Scala 2.13 with Java 17.

An ugly fix would be to clone the container repo and update [Dockerfile ](https://github.com/bitnami/containers/blob/main/bitnami/spark/3.3/debian-11/Dockerfile)to use Java 17 package.
Regarding, Spark with Scala 2.13 - since we don't seem to have a package available on Bitnami repo (Can't seem to list the available packages on https://downloads.bitnami.com/files/stacksmith/). So we unpackage the [latest tar with spark](https://downloads.bitnami.com/files/stacksmith/spark-3.3.1-0-linux-amd64-debian-11.tar.gz
) and copy the /spark with Scala 2.13 package from https://spark.apache.org/downloads.html, repackage and update above Dockerfile to use the new package and create a custom Image.

Any suggestion with a better work around?

**Comment by carrodher** [comment]
We have an internal task to bump the Python and Java versions used by Spark, but in the meantime, your proposal could be valid. You can build your image but using a different Java version, you can obtain it from https://github.com/bitnami/containers/blob/main/bitnami/java/17/debian-11/Dockerfile#L24.

Regarding Scala, since this component is bundled into Spark itself and not added as an external component, you will need to do some changes as the ones you're proposing, but since it is not a supported option out of the box we can't guide during the process.

**Comment by ardesai** [comment]
Thanks for the response @carrodher

**Comment by MohammadForouhesh** [comment]
Any updates on this? it been more than a year since this issue is submited.

**Comment by javsalgar** [comment]
Hi,

I'm afraid our systems do not support bundling different flavors of scala apart from branches.

**Comment by MohammadForouhesh** [comment]
Thanks for your response, 
Can you give some instructions as to how to bundle spark with scala 2.13?

**Comment by MohammadForouhesh** [comment]
@ardesai  had you any success on this? since our use-case is identical to yours, it would be highly appreciated if you could share the Dockerfile / helmchart, or any guidance

**Comment by caldempsey** [comment]
Lost a day debugging issues expecting you guys to be upgraded. This is not solved!
