### ISSUE TITLE
Need help regarding configuring SASL/External-auth

### ISSUE THREAD

**Issue by rohan-97** [bitnami/containers#13639]
### Name and Version

bitnami/openldap:2.6.3-debian-11-r16

Hello, I am trying to install sasl2-bin inside the container to enable SASL authentication.
However I get  apt-get errors while installing package.

Is there any documentation/example/case-study regarding steps to enable and configure SASL External Authentication,
Thanks

**Comment by carrodher** [comment]
The OpenLDAP container is [non-root by default](https://docs.bitnami.com/tutorials/work-with-non-root-containers) (see [Dockerfile](https://github.com/bitnami/containers/blob/main/bitnami/openldap/2.6/debian-11/Dockerfile#L49)) so you need to launch it as `root` in order to be able to execute actions requiring privileges. In the above link, you can find more info about non-root containers and how to work with them.
