### ISSUE TITLE
Kafka supported versions policy

### ISSUE THREAD

**Issue by jouve** [bitnami/containers#13678]
### Name and Version

bitnami/kafka:2.8

### What is the problem this feature will solve?

Hello,

Seeing that Kafka 2.8 image is not released anymore, I'm wondering if there is a policy to know in advance which versions will be supported ?

(The context was I needed for both an update to the base image and kafka 2.8.2 released in september this year)

Having a kind of policy (even if unofficial) would help us plan futures upgrades to Kafka.

### What is the feature you are proposing to solve the problem?

Having a statement , repo wide or per image, about supported versions ?

**Comment by carrodher** [comment]
We follow the same release cadence and supported versions as the upstream projects. In the case of Kafka, according to their [documentation](https://cwiki.apache.org/confluence/display/KAFKA/Time+Based+Release+Plan#TimeBasedReleasePlan-WhatIsOurEOLPolicy?), it is recommended to keep the 3 latest versions:
> Given 3 releases a year and the fact that no one upgrades three times a year, we propose making sure (by testing!) that rolling upgrades can be done from each release in the past year (i.e. last 3 releases) to the latest version.

That's why we currently support Kafka 3.1, 3.2, and 3.3. Once 3.4 (or 4.0) is released in the upstream project, 3.1 will be deprecated on our side.

**Comment by jouve** [comment]
Thanks !
