### ISSUE TITLE
[bitnami/openldap] issue with userPrincipalName

### ISSUE THREAD

**Issue by codedev900** [bitnami/containers#13864]
### Name and Version

 [bitnami/openldap] Release 2.5.13-debian-11-r48

### What steps will reproduce the bug?

I'm trying to add the userPrincipalName, but I don't see an option to do that. I would like to login using the username@domain

### What do you see instead?

userPrincipalName

**Comment by javsalgar** [comment]
Hi,

Could you add more details on how the `userPrincipalName` is configured?

**Comment by codedev900** [comment]
Some of the clients are using userPrincipalName as bindDN, which is perfectly OK with AD, but not with the OpenLDAP, which throws an error upon connect: 

conn=1002 op=1 do_bind: invalid dn (username@example.com)  
send_ldap_result: conn=1002 op=1 p=3  
send_ldap_result: err=34 matched="" text="invalid DN"  
send_ldap_response: msgid=2 tag=97 err=34  
conn=1002 op=1 RESULT tag=97 err=34 text=invalid DN  

I would like to login using the fully qualified username such as username@example.com.

**Comment by codedev900** [comment]
You could map the attributes and objectclasses in /etc/openldap/slapd.conf like such:

map attribute uid sAMAcountName
map objectclass posixAccount user
map objectclass account user
map attribute cn name
map objectclass posixGroup Group
map attribute mail userPrincipalName

**Comment by dgomezleon** [comment]
Hi @codedev900 ,

Since OpenLDAP 2.3, we use [dynamic runtime configuration engine](https://www.openldap.org/doc/admin24/slapdconf2.html), so `slapd.conf` is not used to start the service.

Regarding mapping, I have found some interesting articles:
https://www.pixelstech.net/article/1517623155-OpenLDAP-Proxy----rwm-map-vs-map
https://man7.org/linux/man-pages/man5/slapo-rwm.5.html
https://linux.die.net/man/5/slapd-config
https://git.openldap.org/openldap/openldap/-/blob/master/tests/scripts/test076-authid-rewrite

It seems it uses `rwm-map` now. I would contact OpenLDAP developers for more information about how to configure it.

Note you can use `LDAP_CUSTOM_LDIF_DIR` environment variable with the location of a directory that contains LDIF files that should be used to bootstrap the database. Also, when the container is executed for the first time, it will execute the files with the extension `.sh` located at `/docker-entrypoint-initdb.d`. In order to have your custom files inside the Docker image, you can mount them as a volume.

**Comment by codedev900** [comment]
Thank you for all your help!
