### ISSUE TITLE
Can't install additional jars - curl: command not found

### ISSUE THREAD

**Issue by ustas0** [bitnami/containers#13905]
### Name and Version

bitnami/spark:3.3

### What steps will reproduce the bug?

https://hub.docker.com/r/bitnami/spark - Installing additional jars
```Dockerfile
FROM bitnami/spark
USER 1001
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.704/aws-java-sdk-bundle-1.11.704.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.704.jar
```

### What is the expected behavior?

I want to download additional jars from maven repo

### What do you see instead?

Error "curl : command not found"

### Additional information

You remove it here: https://github.com/bitnami/containers/blob/main/bitnami/spark/3.3/debian-11/Dockerfile

**Comment by carrodher** [comment]
Hi, we have been working on removing non-needed dependencies to have more secure containers, reducing the attack surface and the container size. In this case, `curl` is not used by the PostgreSQL application but by a custom script you're loading assuming that `curl` is installed in the container. We reviewed when `curl` (and other packages) are used by the main application and remove it when it was not used.

You can use the `install_packages` script to install it if it is needed for your use case when creating your custom image based on Bitnami’s or using `curl` as part of any custom script.
Please take into account, Bitnami containers are non-root by default, in order to be able to install packages you will need to run the container as root (at least when installing the package).

In your specific case, you can do something like
```Dockerfile
FROM bitnami/spark
USER root
RUN install_packages curl
USER 1001
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.704/aws-java-sdk-bundle-1.11.704.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.704.jar
```

**Comment by ustas0** [comment]
Thanks for your answer. I've solved my problem by cloning your GitHub repo
and building my own image. I think you have to reflect this case in the
description of the spark image on Docker Hub.

I want to thank your team. I use your images too often and I am very happy.

чт, 17 нояб. 2022 г. в 00:57, Carlos Rodríguez Hernández <
***@***.***>:

**Comment by Sejmou** [comment]
could somebody update the [README](https://github.com/bitnami/containers/tree/main/bitnami/spark#installing-additional-jars)?
the `install_packages` part for getting `curl` installed is still missing there 😅

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
