### ISSUE TITLE
Vulnerabilities detected with snyk

### ISSUE THREAD

**Issue by msaustral** [bitnami/containers#19881]
### Name and Version

containers/bitnami/nginx/1.23/debian-11/

### What steps will reproduce the bug?

Make a personal image and upload it on docker hub with snyk

### What is the expected behavior?

To no have any vulnerability, at least critical or high 

### What do you see instead?

Snyk detect 4 critical 4 high and 22 mayor vulnerabilities and must of them are because of the os debian-11

### Additional information

None of the vulnerabilities has corrections according to snyk but how can we try this image with another os, let say Ubuntu? can it be done?
Can Bitnami correct this issue using Debian?

![image](https://user-images.githubusercontent.com/46203943/211940753-65d7504a-f829-45a5-b37c-ef3a123fcb06.png)

**Comment by carrodher** [comment]
Hi, unfortunately, those security vulnerabilities are not fixed by the OS or the application itself, so although we built the images on a regular basis to provide the latest version of system packages, this kind of CVE will be reported while there is no new version patching the issue in the OS or the application. [Here](https://docs.bitnami.com/kubernetes/open-cve-policy/) you can find more info about this topic.

The Bitnami Application Catalog (OpenSource) is based on Debian 11 but Bitnami, as part of VMware, provides a custom container and Helm Charts catalog based on the desired base image (generic distro such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04, 20.04 & 22.04, RedHat UBI 8 & 9, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

**Comment by msaustral** [comment]
Hi @carrodher thank you for the information, we do not see any price on the VMware Tanzu Application Catalog.
We filed the form and wait to someone to contact us, thank you

**Comment by carrodher** [comment]
Thanks, I don't know what is the process once filled the form, but someone will contact you to provide all the information.
