### ISSUE TITLE
[bitnami/schema-registry] Improve docs

### ISSUE THREAD

**Issue by ETisREAL** [bitnami/containers#21206]
### Name and Version

bitnami/schema-registry

### What is the problem this feature will solve?

There is absolutely no documentation on how to use the docker image, set it up via docker compose and link it with kafka. This is absolutely useless in this format, how the hell am I supposed to know what to do? The confluent documentation and set-ups only work for their images

### What is the feature you are proposing to solve the problem?

WRITE DOCUMENTATION

### What alternatives have you considered?

Useing Confluent images

**Comment by carrodher** [comment]
Thanks for using this container image and sorry for the inconvenience. Unfortunately, we have an extensive catalog and we can't provide documentation for all the applications. In the same way, the binary/source code is not modified from what is provided upstream, so the upstream documentation should be valid in most cases.

In order to see some examples of how this container image can be connected to other containers such as kafka and zookeeper, you can take a look at the docker-compose.yaml files present in this repo, for instance https://github.com/bitnami/containers/blob/main/bitnami/schema-registry/7.3/debian-11/docker-compose.yml

**Comment by OneCricketeer** [comment]
That compose file shows a plaintext connection. What about SSL/SASL, which is more common for enterprise Kafka installations?

**Comment by carrodher** [comment]
We updated the readme file of our schema-registry container adding a section on how to configure it using environment variables. Please find below the direct link to this section

https://github.com/bitnami/containers/tree/main/bitnami/schema-registry#configuration

Hope this helps!

**Comment by ETisREAL** [comment]
> We updated the readme file of our schema-registry container adding a section on how to configure it using environment variables. Please find below the direct link to this section
> 
> https://github.com/bitnami/containers/tree/main/bitnami/schema-registry#configuration
> 
> Hope this helps!

Thank you. This is much better
