### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by esstat17** [bitnami/containers#21802]
### Name and Version

bitnami/postgresql:latest

### What steps will reproduce the bug?

Hi Bitnami folks!

I encountered this issue using image: docker.io/bitnami/postgresql:15 and also the latest version, which the logs say

`mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied`

My docker-compose.yml looks like this
```yaml
volumes:
      - './path/var/postgresql:/bitnami/postgresql'
```
it looks like it has no problem with the file system when using the Official postgres image

Did I miss something? this path `./path/var/postgresql` is 100% existing and I have file permissions, perhaps it has something to do with UID, GID inside the container.

### What do you see instead?
```
discourse1-postgresql-1  | mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
```

**Comment by carrodher** [comment]
Please note the Bitnami container images are non-root by default, this means any directory where the application needs to write needs to be set to the `root` group (GID 0) so the random user (UID 1001 by default) is able to write there since the random user always belongs to the root group.

Can you try by setting `root` as the group for your local directory?

[Here](https://docs.bitnami.com/tutorials/work-with-non-root-containers) you can find more info about non-root containers.

**Comment by esstat17** [comment]
@carrodher thank you for your reply, I appreciate it, for some reasons it works,
`sudo chown -R 1001:0 ./path/ `


FYI, my UID is actually 1000 (not 1001), so perhaps passing an environment variable $UID to the container instead of fix value UID 1001 as default is ideal?

also I love the idea of non-root user for containers for security reasons.

I am not sure exactly how to use your images since it has file permission issue, 

so it is advisable to change owner ?
`sudo chown -R 1001:0 ./path/`

**Comment by carrodher** [comment]
You can leave the UID as it is in your local directory, the random user (1000, 1001 or any other) should belong to the root group, so setting the ownership of the local directory to the root group (GID 0) should be enough regardless of the UID

**Comment by esstat17** [comment]
Thank you! @carrodher I appreciate it.
