### ISSUE TITLE
security issues with CVV V3 more than 7 with latest image

### ISSUE THREAD

**Issue by ankursrivastva** [bitnami/containers#22171]
### Name and Version

bitnami/mariadb-galera:10.9.4-debian-11-r27

### What steps will reproduce the bug?

running jfrog x ray scan will reporoduce the issue
[Docker_rmrsp-bitnami-mariadb-galera-10.9.4-debian-11-r27_Security_Export.csv](https://github.com/bitnami/charts/files/10530379/Docker_rmrsp-bitnami-mariadb-galera-10.9.4-debian-11-r27_Security_Export.csv)

### What do you see instead?

please fix the issue or let us know in which release the fix will come

**Comment by ankursrivastva** [comment]
Hi @carrodher, thanks for the reply. Since, its security vulneraibilties which is restricting us to use this image in production environment. could you please suggest us the next steps or hwo can we fix it by ourselves ?

**Comment by carrodher** [comment]
This Bitnami Application Catalog (OpenSource) is based on Debian 11 and container images are rebuilt regularly in order to include the latest versions of the system packages, on our side, there is nothing we can do apart from that. You can fill an issue in Debian itself or in the affected packages' bug trackers in order to ask for new versions.

Apart from that, we also provide a custom container and Helm Charts catalog based on the desired base image (generic distros such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04, 20.04 & 22.04, RedHat UBI 8 & 9, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog). In different distros, the number of vulnerabilities could be different since the release cadence of the system packages is not the same.
