### ISSUE TITLE
[bitnami/spark] Critical vulnerabilities in 3.3.1-debian-11

### ISSUE THREAD

**Issue by brsolomon-deloitte** [bitnami/containers#24144]
### Name and Version

bitnami/spark:3.3.1-debian-11-r41

### What steps will reproduce the bug?

`bitnami/spark:3.3.1-debian-11-r41` has multiple critical security vulnerabilities including Text4Shell due to its use of outdated JARs. I suppose this comes from the underlying `spark-3.3.1-6-linux-${OS_ARCH}-debian-11` component in the image build.

### What is the expected behavior?

Update JARs.

### What do you see instead?

Outdated JAR versions.

org.apache.hadoop_hadoop-common version 3.3.2 -> CVE-2022-25168
org.apache.commons_commons-text version 1.9 -> CVE-2022-42889
com.fasterxml.jackson.core_jackson-databind version 2.6.7.4 has 7 vulnerabilities

From `docker container run -it --rm --entrypoint=bash bitnami/spark:3.3.1-debian-11-r41`:

```
$ ls jars/commons-text*
jars/commons-text-1.9.jar
$ ls jars/hadoop-client-*
jars/hadoop-client-api-3.3.2.jar  jars/hadoop-client-runtime-3.3.2.jar
```

Note that the `jackson-databind` version actually comes from `/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.1026.jar`.

**Comment by carrodher** [comment]
Hi, unfortunately, those security vulnerabilities are not fixed by the OS or the application itself, so although we built the images on a regular basis to provide the latest version of system packages, this kind of CVE will be reported while there is no new version patching the issue in the OS or the application. [Here](https://docs.bitnami.com/kubernetes/open-cve-policy/) you can find more info about this topic.

Apart from that, we are working on the release of a new Spark version (3.3.2) which was recently released in the upstream project, [here](https://spark.apache.org/releases/spark-release-3-3-2.html) you can find the release notes of this version.

The Bitnami Application Catalog (OpenSource) is based on Debian 11 but Bitnami, as part of VMware, provides a custom container and Helm Charts catalog based on the desired base image (generic distros such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04, 20.04 & 22.04, RedHat UBI 8 & 9, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

**Comment by brsolomon-deloitte** [comment]
Closing with the publication of the bitnami/spark 3.3.2 image.
