### ISSUE TITLE
[bitnami/fluent-bit] Remove EXPOSE from Dockerfile

### ISSUE THREAD

**Issue by brki** [bitnami/containers#25752]
### Name and Version

bitnami/fluent-bit:2.0.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

On Cloud foundry, try to run a Docker file based on this image, listening on a port other than 2020.

It won't work out nicely.

### What is the expected behavior?

I expect being able to specify my own EXPOSE in a Dockerfile that bases on this one.  Or to let Cloud foundry use its own port listening logic, if there is no EXPOSE.

### What do you see instead?

The Cloud foundry dockerized app listens on port 2020.

### Additional information

In the [Cloud foundry docs](https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html#-port-configuration), they say that the port that will used for listening is taken from the EXPOSE present in the Dockerfile.  Maximum one EXPOSE is taken into consideration, and apparently they take the first one.

It's a questionable design by Cloud foundry, I think.

But, is there anything against removing that EXPOSE from the Dockerfile? The `docker-compose.yaml` explicitly maps the port anyway.

I see the fluent/fluent-bit Dockerfile does not use EXPOSE. Unfortunately I can't add CA certificates and run `update-ca-certificates` with a Dockerfile based on their non-debug image, because it is distroless.

My Cloud foundry restricts the allowed ports to be used, so that's why I can't happily use port 2020.

**Comment by carrodher** [comment]
Unfortunately, that's something to check with Cloud foundry since the container images are designed to be consumed in different ways (standalone, docker-compose, Helm charts, etc). As the [`EXPOSE` directive](https://docs.docker.com/engine/reference/builder/#expose) is extensively used and something contemplated in the standard, I don't see any advantage removing it just for a third-party service not handling it properly

**Comment by brki** [comment]
Well, `EXPOSE` **is** known to be a bit problematic as it is now, see for example [this languishing issue](https://github.com/moby/moby/issues/3465).  I'd argue that EXPOSE should only be used at the last moment.  If it's probable that someone will create a new image `B` based on image `A`, then it's better if image `A` does not use `EXPOSE`.

All of the different container interfaces you mentioned (standalone, docker-compose, Helm, etc) provide a way to map  ports, but unfortunately the current Dockerfile implementation doesn't allow one to un-`EXPOSE` a port.

**Comment by carrodher** [comment]
After checking with the team, the majority view is that it's quite useful to have a curated section with the ports that you expect to expose to make the app work without going to docs. As mentioned previously, it seems it is this third-party service that one taking a bad decision here since “pick the first expose directive only” goes against the fundamentals of containers, which are based on layers.

Maybe a workaround using a multistage container works
```console
$ cat Dockerfile
FROM bitnami/fluent-bit:2.0.9 AS builder

FROM bitnami/minideb:latest
COPY --from=builder / /
EXPOSE 8080

$ docker inspect test:test | grep Exposed -A2
            "ExposedPorts": {
                "8080/tcp": {}
            },
```

**Comment by brki** [comment]
@carrodher thanks for the suggestion. Indeed, I did end up doing that (using `scratch` instead of `bitnami/minideb:latest`).

Adding these back in were necessary too:
```
ENV PATH="/opt/bitnami/fluent-bit/bin:$PATH"
WORKDIR /opt/bitnami/fluent-bit
USER 1001
```

I appreciate the work that you do for this! Thank you!
