### ISSUE TITLE
Keycloak V19 support

### ISSUE THREAD

**Issue by chih-chen** [bitnami/containers#2719]
Hello! 

Keycloak just released version 19, any plan on supporting it officially by bitnami in short term? 👀 

(Not sure if here is the right place to ask this question, sorry in advance for any inconvenience) 

Thanks!!

**Comment by rafariossaa** [comment]
Hi,
  Yes, you can ask that kind of questions here, don't worry.
  We track upstream updates, so yes, keycloak 19 is on our radar and will be released soon.

**Comment by manuschillerdev** [comment]
Would the current helm-chart need any updates as well, or is Keycloak 19 a drop-in replacement, once it will be released?

**Comment by carrodher** [comment]
As it is a new major version we need to perform different manual actions in our internal test & release pipeline, that's why the new version is not automatically released.
As part of those manual actions, if changes in the Helm chart are needed we will create a PR in the bitnami/charts repository with the required changes and bump the chart version accordingly, i.e using a new major `X.0.0` if there is not backward compatibility or major changes

**Comment by manuschillerdev** [comment]
thanks for the clarification on the relation between this image and the chart everybody!

**Comment by lhuynh112** [comment]
Hello, I got keycloak successfully deployed but I can't seem to use the user/user login. Am I missing something?

**Comment by gongomgra** [comment]
Hi @chih-chen,

Just a quick note to let you know that we released a new keycloak image for branch 19. You can pull it using the next command

```
docker pull bitnami/keycloak:19.0.1-debian-11-r2
```

@lhuynh112 . I started a new `docker-compose` deployment with the latest image and I was able to log into the Admin panel with the default username/password mentioned in our readme file. Can you clean up all the volumes from previous executions, and test the latest image? If you continue having issues, please open a new Github issue for this. Our support team will be glad of helping you with your issue.

https://github.com/bitnami/containers/tree/main/bitnami/keycloak#admin-credentials
