### ISSUE TITLE
SetUp bitnami/ksql using docker compose

### ISSUE THREAD

**Issue by aboah** [bitnami/containers#27394]
### Name and Version

bitnami/ksql

### What architecture are you using?

arm64

### What steps will reproduce the bug?
```yaml
  ksqldb:
    image: 'bitnami/ksql:latest'
    container_name: ksqldb
    ports:
      - '8088:8088'
    environment:
      - KSQL_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - './ksql/data:/bitnami/ksql'
    networks:
      - bitnami-network
```

### What do you see instead?
```
ksql 13:03:45.43 INFO  ==> ** Starting KSQL setup **
ksql 13:03:45.44 INFO  ==> Validating settings in KSQL_* env vars
Starting KSQL setup mkdir: cannot create directory '/bitnami/ksql/data': Permission denied


2023-03-14T13:03:45.446432152Z ksql 13:03:45.43 INFO  ==> ** Starting KSQL setup **
2023-03-14T13:03:45.451733360Z ksql 13:03:45.44 INFO  ==> Validating settings in KSQL_* env vars
2023-03-14T13:03:45.474251712Z mkdir: cannot create directory '/bitnami/ksql/data': Permission denied
```
### Additional information

The following no longer exist in docker registry hub but very necessary for implementing bitnami compatible streaming applications.

1) bitnami/kafka-connect:latest
2) bitnami/ksql-server:latest
3) bitnami/ksql-cli

**Comment by carrodher** [comment]
Bitnami containers are non-root by default, which means any file/dir used by the application should belong to the _root_ group since the random user (_1001_ by default) is part of this _root_ group. You should adapt the permission of your local directory so the _root_ group is the owner.

You can find more info about non-root containers at
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

**Comment by aboah** [comment]
Please how can I get these images
bitnami/kafka-connect:latest
bitnami/ksql-server:latest
bitnami/ksql-cli
