### ISSUE TITLE
MSSQL Server

### ISSUE THREAD

**Issue by pomland-94** [bitnami/containers#28333]
### Name and Version

bitnami/mssql:latest

### What is the problem this feature will solve?

Hey,
I wan't to create a MSSQL Container and Helm Chart and wan't to sponsor it to you, is it possible to get all your script which you are use for all the other containers? So I can build a container with mysql server or is this not possible and I have to write my own Scripts to initialize the Container and the Application? As baseos I'll use "bitnami/minideb".

### What is the feature you are proposing to solve the problem?

MSSQL Server Docker Container and Kubernetes Helm Chart

**Comment by carrodher** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; this process could take some time due to limited resources. In the meantime, we will add the 'on-hold' label to prevent the stale bot from closing this issue.

Unfortunately, contributions to the containers' source code are not possible, which needs to be performed by the Bitnami team.

**Comment by carrodher** [comment]
> So it is not possible to create a Container Image with the Bitnami libs on my own?

You can replicate the initialization behavior with the scripts present in this repository as well as the Dockerfile and docker-compose, what is not public here is the compiled tarball of the application and components

**Comment by pomland-94** [comment]
I would compile MSSQL on my own.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
