### ISSUE TITLE
Jasper Reports fails after stop/start

### ISSUE THREAD

**Issue by kalatchev** [bitnami/containers#28415]
### Name and Version

bitnami/jasperreports:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run a container with `-e JASPERREPORTS_USE_ROOT_URL=true`
2. `docker stop container-name-here`
3. `docker start container-name-here`

See attached file for full docker command (only sensitive information is replaced).
[bitnami-jasper-run-command.txt](https://github.com/bitnami/containers/files/11083341/bitnami-jasper-run-command.txt)

### What is the expected behavior?

I am expecting the container to start normally.

### What do you see instead?

I am getting an error 
```bash
...
sed: can't read /opt/bitnami/tomcat/webapps/ROOT/index.jsp: No such file or directory
```

See attached log (I've used `-e BITNAMI_DEBUG=true `
[bitnami-jasper-debug-error.txt](https://github.com/bitnami/containers/files/11083316/bitnami-jasper-debug-error.txt)

### Additional information

The Jasper Reports version is 8.1.

**Comment by kalatchev** [comment]
> If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

Sure @carrodher, I would like to do it, but unfortunately I'm not able to do is due to my superficial knowledge of how your scripts are made. The only clue for me is:
https://github.com/bitnami/containers/blob/f52e9d9d91d6dd99ff243e40d3e0b210864f042d/bitnami/jasperreports/8/debian-11/rootfs/opt/bitnami/scripts/libjasperreports.sh#L421-L426 

I am not sure why symlink doesn't work after stop / start.

If you could get me a further directions how I could debug it and/or fix it, I certainly will give my five cents to the project :smile:

**Comment by msladek** [comment]
@kalatchev I experience the same issue as you described here. have you found a solution for it?

**Comment by fattazzo** [comment]
@kalatchev 

The issue was closed but without finding a solution. I also ran into this problem and even though it's late I would like to give you my solution.

I edited the file `libjasperreports.sh` and i change this lines:

```dockerfile
    # Make Tomcat redirect to /jasperserver
    replace_in_file "$BITNAMI_ROOT_DIR/tomcat/webapps/ROOT/index.jsp" '<%\s*$' '<%\nresponse.sendRedirect("/jasperserver");'

    # Move JasperServer to default Tomcat URL
    if is_boolean_yes "${JASPERREPORTS_USE_ROOT_URL}"; then
        rm -rf "$BITNAMI_ROOT_DIR/tomcat/webapps/ROOT"
        rm "$BITNAMI_ROOT_DIR/tomcat/webapps/jasperserver"
        ln -s "$JASPERREPORTS_BASE_DIR" "$BITNAMI_ROOT_DIR/tomcat/webapps/ROOT"
    fi
``` 

with this:

```dockerfile
    # Move JasperServer to default Tomcat URL
    if is_boolean_yes "${JASPERREPORTS_USE_ROOT_URL}"; then
        rm -rf "$BITNAMI_ROOT_DIR/tomcat/webapps/ROOT"
        rm "$BITNAMI_ROOT_DIR/tomcat/webapps/jasperserver"
        ln -s "$JASPERREPORTS_BASE_DIR" "$BITNAMI_ROOT_DIR/tomcat/webapps/ROOT"
    else
        # Make Tomcat redirect to /jasperserver
        replace_in_file "$BITNAMI_ROOT_DIR/tomcat/webapps/ROOT/index.jsp" '<%\s*$' '<%\nresponse.sendRedirect("/jasperserver");'
    fi
``` 

Just copy `libjasperreports.sh` from `/opt/bitnami/scripts` to local dir, change the lines and remap the file in docker-compose.yml as volume:

```dockerfile
volumes
  - ./yourlocaldir/libjasperreports.sh:/opt/bitnami/scripts/libjasperreports.sh
``` 

Why tihs change? Because what happened step by step was:

First start:

- `index.jsp` edited with redirect to jasperserver --> **OK**
- if JASPERREPORTS_USE_ROOT_URL=true, remove ROOT and jasperserver apps and link jasperserver to ROOT --> **OK**

Restart:

- `index.jsp` edited with redirect to jasperserver --> **ERROR!! This is because the jasperserver app does not contain any index.jsp**

I hope this helps someone again! Thanks
