### ISSUE TITLE
[bitnami/grafana] not picking up admin password from secret

### ISSUE THREAD

**Issue by josvazg** [bitnami/containers#28615]
### Name and Version

bitnami/grafana:9.4.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the container image as a pod for Kubernetes mounting the value of  `GF_SECURITY_ADMIN_PASSWORD` as a secret.
2. Try to log in with the password set in the secret.
3. The **login attempt fails**.
4. Check the environment variables of the pod, the env var `GF_SECURITY_ADMIN_PASSWORD` is correctly set.
5. Run on the pod `grafana-cli admin reset-admin-password $GF_SECURITY_ADMIN_PASSWORD`.
6. Now login works as expected, but not before.

### What is the expected behavior?

Admin login should work with the password store in the secret out of the box.

### What do you see instead?

Admin login only works after you explicitly reset it manually with the `grafana-cli` tool. 

### Additional information

Will attach our deployment YAML as an example in case there is some mistake in there that explains this behavior rather than a bug.

**Comment by gongomgra** [comment]
Hi @josvazg,

I'm afraid I have not being able to reproduce your issue using the YAML files you shared and my own custom password from a secret.

**Comment by josvazg** [comment]
Ok, lets close it. It might have been something between the keyboard and chair this time.

**Comment by rafalkrupinski** [comment]
I have similar issue, grafana doesn't pick up the admin password from grafana.ini mounted from configMap

**Comment by javsalgar** [comment]
Could you share the exact steps to reproduce it? We were unable to do so in our side

**Comment by rafalkrupinski** [comment]
I was able to find the problem, and it's not a bug with Grafana.

The problem was coming from these conditions:
- a wrong configuration that didn't pass the GF_SECURITY_ADMIN_PASSWORD variable
- mounting a volume at /var/lib/grafana
- not destroying the deployment after the first run

In result, Grafana took its default admin password and saved it in its internal database in `/var/lib/grafana`, and ignored the environment variable when I tried to fix it by calling `kubectl apply -k`  the second time.
