### ISSUE TITLE
[bitnami/keycloak] m1 mac version of bitnami/keyclaok.16.1.1

### ISSUE THREAD

**Issue by sirAlexander** [bitnami/containers#29329]
### Name and Version

bitnami/keycloak/16.1

### What architecture are you using?

arm64

### What steps will reproduce the bug?

how can I go about building locally on my mac m1 a previous version of bitnami keycloak. version 16.1.1 to be exact

### What do you see instead?

a working deployment when keycloak 16.1.1 is deployed locally on my m1 mac

**Comment by javsalgar** [comment]
Hi,

I'm afraid that, if there is no arm64 version of keycloak in our catalog, it is because we found issues when building it and therefore we couldn't add it. If you want to try, you can check the upstream building instructions for keycloak and try using of the Bitnami container replacing the `/opt/bitnami/keycloak` directory.
