### ISSUE TITLE
[bitnami/matomo] Custom image creation not working

### ISSUE THREAD

**Issue by Prithivi-Rajan** [bitnami/containers#3234]
### Name and Version

bitnami/matomo:4.11.0

### What steps will reproduce the bug?

1. I'm building an image keeping bitnami/matomo:4.11.0 as a base and added a single line of code to enable trace(`ENV NAMI_DEBUG --log-level=trace`) and trying to locally run a container with help of docker desktop. But I could see the below error when trying to do that.
2. I have used the docker-compose file given in this directory to build the database and matomo and that works well. Once I stop the running one which is pulled from the docker hub and start to run my custom image error is seen.

### What is the expected behavior?

The container should be running up.

### What do you see instead?
```
/opt/bitnami/scripts/matomo/entrypoint.sh: line 31: exec: -e: invalid option
exec: usage: exec [-cl] [-a name] [command [argument ...]] [redirection ...]
```

**Comment by fmulero** [comment]
Hi @Prithivi-Rajan 

In order to extend the image, [here](https://github.com/bitnami/containers/blob/68a5526869f5fbcdef44727cd15c2dac56de4c6a/bitnami/apache/README.md#extend-this-image) you've got an example with the apache image.

Please keep in mind this is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.
