### ISSUE TITLE
[bitnami/logstash] ENV LOGSTASH_MOUNTED_CONF_DIR and LOGSTASH_MOUNTED_PIPELINE_CONF_DIR is very unfriendly.

### ISSUE THREAD

**Issue by ldcsaa** [bitnami/containers#34561]
### Name and Version

bitnami/logstash:8.7.1

### What architecture are you using?

None

### What steps will reproduce the bug?
conf files were overrided when every times startup container, because container runs `logstash_create_sample_pipeline_config_file` script.
just mount `config `and `pipeline `dir:
```
-v /my/config/apth:/opt/bitnami/logstash/config
-v /my/pipeline/apth:/opt/bitnami/logstash/pipeline
```

if mount to /bitnami/logstash/config (pipeline), it only copy *.conf file.

### What is the expected behavior?

remove ENV LOGSTASH_MOUNTED_CONF_DIR and LOGSTASH_MOUNTED_PIPELINE_CONF_DIR

### What do you see instead?

 ```
# !! these codes would causes manual mount not work !!
# conf files were overrided when every times startup container
# -v /my/config/apth:/opt/bitnami/logstash/config
# -v /my/pipeline/apth:/opt/bitnami/logstash/pipeline

if ! is_mounted_dir_empty "$LOGSTASH_MOUNTED_CONF_DIR"; then
	info "Mounted setting files detected"
	cp -Lr "$LOGSTASH_MOUNTED_CONF_DIR"/. "$LOGSTASH_CONF_DIR"
fi

if is_boolean_yes "$LOGSTASH_ENABLE_MULTIPLE_PIPELINES"; then
	if [[ -e "${LOGSTASH_MOUNTED_CONF_DIR}/pipelines.yml" ]]; then
		info "Detected mounted 'pipelines.yml' configuration file for multiple pipelines"
	else
		logstash_create_sample_pipelines_yml_file
	fi
fi

if [[ -n "$LOGSTASH_PIPELINE_CONF_FILENAME" && -e "${LOGSTASH_MOUNTED_PIPELINE_CONF_DIR}/${LOGSTASH_PIPELINE_CONF_FILENAME}" ]]; then
	info "Detected mounted '${LOGSTASH_PIPELINE_CONF_FILENAME}' pipeline configuration file"
	cp -L "${LOGSTASH_MOUNTED_PIPELINE_CONF_DIR}/${LOGSTASH_PIPELINE_CONF_FILENAME}" "$LOGSTASH_PIPELINE_CONF_DIR"
elif ! is_mounted_dir_empty "$LOGSTASH_MOUNTED_PIPELINE_CONF_DIR"; then
	info "Detected mounted pipeline configuration files"
	cp -Lr "$LOGSTASH_MOUNTED_PIPELINE_CONF_DIR"/*.conf "$LOGSTASH_PIPELINE_CONF_DIR"
elif [[ -e "${LOGSTASH_MOUNTED_CONF_DIR}/${LOGSTASH_PIPELINE_CONF_FILENAME}" ]]; then
	# Support for legacy configuration before configurations were separated into 'config' and 'pipeline'
	warn "Detected mounted '${LOGSTASH_MOUNTED_CONF_DIR}/${LOGSTASH_PIPELINE_CONF_FILENAME}' pipeline configuration file in legacy directory."
	warn "Support for this configuration may be deprecated in a future version of this image. Please mount the file to '${LOGSTASH_MOUNTED_PIPELINE_CONF_DIR}/${LOGSTASH_PIPELINE_CONF_FILENAME}' instead."
	cp -Lr "$LOGSTASH_MOUNTED_CONF_DIR"/*.conf "$LOGSTASH_PIPELINE_CONF_DIR"
else
	logstash_create_sample_pipeline_config_file
fi
```

**Comment by migruiz4** [comment]
Hi @ldcsaa,

Thank you for reporting this issue! We are currently working on a fix that includes several Logstash pipeline mount logic changes.

The proposed changes include:
* All files mounted at '/bitnami/logstash/pipeline' will be mounted, because logstash merges all of them in runtime, not only *.conf files.
* Only generate a sample pipeline file if '/opt/bitnami/logstash/pipeline' is empty. This way, errors won't be displayed if users mount their pipeline files at '/opt/bitnami/logstash/pipeline' instead of '/bitnami/logstash/pipeline'.

**Comment by ldcsaa** [comment]
I had pulled the latest version, but the next codes still would overrided 
`-v /my/path/pipelines.yml:/opt/bitnami/logstash/conf/pipelines.yml` 
by ` logstash_create_sample_pipelines_yml_file`

```
    if is_boolean_yes "$LOGSTASH_ENABLE_MULTIPLE_PIPELINES"; then
        if [[ -e "${LOGSTASH_MOUNTED_CONF_DIR}/pipelines.yml" ]]; then
            info "Detected mounted 'pipelines.yml' configuration file for multiple pipelines"
        else
            logstash_create_sample_pipelines_yml_file
        fi
    fi
```

**Comment by migruiz4** [comment]
The fix is only for `/opt/bitnami/logstash/pipeline` folder, which is a special case because as you mentioned it is not only about mounting a single file `logstash.conf`, but all files in that folder would be merged and not necessarily need to have the `.conf` extension.

In order to mount `pipelines.yml` and other conf files, please use the `/bitnami/logstash/config/pipelines.yml` path instead.

**Comment by ldcsaa** [comment]
Why you create `LOGSTASH_MOUNTED_CONF_DIR` and `LOGSTASH_MOUNTED_PIPELINE_CONF_DIR` env ? 
I saw other images like bitnami\elasticsearch, bitnami\prometheus etc. were not has this env .

**Comment by ldcsaa** [comment]
ok, thanks~
