### ISSUE TITLE
Considerations for monorepo from a user's perspective

### ISSUE THREAD

**Issue by docktermj** [bitnami/containers#3697]
### What is the problem this feature will solve?

I'm providing feedback based on the link given in this article:  https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html

From a customer's perspective:

1. **Cloning/Forking:** If a customer wants to clone or fork a repository for a specific Dockerfile, their clone/fork contains every Dockerfile made by Bitnami in the monorepository.  So much for small, manageable repositories.  It also makes it harder to determine the number of forks for a particular Dockerfile, as well as watchers and stars. Your customers are losing visibility into acceptance and modification of your Dockerfiles.
2. **Issue management:** If a customer wants to see if a particular Dockerfile is without issue,  how is this discerned from https://github.com/bitnami/containers/issues?  It's not guaranteed that the "[container-name]" is prepended. I see that topic are being added to every issue.  Is that the mechanism?
3. **Versioning:** How is versioning managed?   In the prior system the https://github.com/bitnami/bitnami-docker-postgresql/tags would indicate the version of the code used in building Docker images on DockerHub.   How does your customer correlate what is seen on DockerHub with the correct version of the code in https://github.com/bitnami/containers?

By the way,  I love Bitnami's work.  I consider Bitnami a leader in Docker containers.  So I'm very sensitive to how Bitnami manages its Docker container development. I am curious to find out if you have truly solved problems or just traded one set of problems for a different set of problems that burden your customer.

**Comment by carrodher** [comment]
Thanks for the feedback! Please see below an inline answer to each one of the topics. As a general comment, since the usage of the different Bitnami containers is free we prefer to talk about users instead of customers 😉 
 
> 1. **Cloning/Forking:** If a customer wants to clone or fork a repository for a specific Dockerfile, their clone/fork contains every Dockerfile made by Bitnami in the monorepository.  So much for small, manageable repositories.  It also makes it harder to determine the number of forks for a particular Dockerfile, as well as watchers and stars. Your customers are losing visibility into acceptance and modification of your Dockerfiles.

That is one of the cons that is difficult to solve. We applied different actions when moving the different distributed repositories into this monorepo to obtain a manageable size so it can be pulled/forked without big issues.
Regarding the traction of a specific container, the popularity/usage can be measured by the number of pulls. This information is provided in the DockerHub UI, for instance at https://hub.docker.com/r/bitnami/wordpress

> 2. **Issue management:** If a customer wants to see if a particular Dockerfile is without issue,  how is this discerned from https://github.com/bitnami/containers/issues?  It's not guaranteed that the "[container-name]" is prepended. I see that topic are being added to every issue.  Is that the mechanism?

Users should be able to see all the issues/PRs associated with a specific application by looking for its label, for example, in the case of WordPress: https://github.com/bitnami/containers/labels/wordpress

> 3. **Versioning:** How is versioning managed? In the prior system the https://github.com/bitnami/bitnami-docker-postgresql/tags would indicate the version of the code used in building Docker images on DockerHub. How does your customer correlate what is seen on DockerHub with the correct version of the code in https://github.com/bitnami/containers?

Information about the versions can be found in different ways, see below some of them:
- ["Supported tags and respective Dockerfile links"](https://github.com/bitnami/containers/tree/main/bitnami/node#supported-tags-and-respective-dockerfile-links) section in the different READMEs
- `tags-info.yaml` inside every branch, for instance https://github.com/bitnami/containers/blob/main/bitnami/node/18/debian-11/tags-info.yaml
- Commits message, i.e https://github.com/bitnami/containers/commits/main/bitnami/node

----------------------------

When moving from one approach to the other we were aware that some features could be missed, but in the end, the overall balance was positive about the migration to the monorepo. For those missed features we tried to look for an equivalent approach like the mentioned ones.
