### ISSUE TITLE
Add ProcessMaker container image?

### ISSUE THREAD

**Issue by zajimumaaa** [bitnami/containers#37498]
### Name and Version

n/a

### What is the problem this feature will solve?

Deploy ProcessMaker via container instead of VMs

### What is the feature you are proposing to solve the problem?

Create container image for ProcessMaker

### What alternatives have you considered?

Tried the ProcessMaker VM from bitnami but much prefer containerized deployment if possible.

Apologize if this is not the right place to ask or you are not accepting image request.

**Comment by carrodher** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; this process could take some time due to limited resources. In the meantime, we will add the 'on-hold' label to prevent the stale bot from closing this issue.

Unfortunately, contributions to the containers' source code are not possible, which needs to be performed by the Bitnami team.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
