### ISSUE TITLE
pytorch:1.13.1 image contains wrong version of pytorch

### ISSUE THREAD

**Issue by maxmealy** [bitnami/containers#37779]
### Name and Version

bitnami/pytorch:1.13.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```console
$ docker pull bitnami/pytorch:1.13.1
1.13.1: Pulling from bitnami/pytorch
29eea4fa7c94: Pull complete
Digest: sha256:c15ed9d3ad90289c39e55fb3c04dd18a47bb8ce4af2fc5b70f39548b5607fe15
```

```console
$ docker run bitnami/pytorch:1.13.1 pip freeze
torch              2.0.0+cpu
```

### What is the expected behavior?

torch 1.13.1+cpu

### What do you see instead?

torch 2.0.0+cpu

**Comment by carrodher** [comment]
Thanks for reporting this issue. Effectively, we checked that something is wrong with the latest container images in branch 1.

Starting from `1.13.1-debian-11-r30`, all the images in branch 1 contain a wrong PyTorch binary version since it seems we're bundling PyTorch 2.x.x instead of 1.x.x:
```console
$ docker run bitnami/pytorch:1.13.1-debian-11-r30 pip freeze | grep torch
torch==2.0.0+cpu

$ docker run bitnami/pytorch:1.13.1-debian-11-r36 pip freeze | grep torch
torch==2.0.0+cpu
```

Since those are the latest version for branch 1, all the rolling tags are stuck in those wrong container images:
```console
$ docker run bitnami/pytorch:1.13.1 pip freeze | grep torch
torch==2.0.0+cpu

$ docker run bitnami/pytorch:1 pip freeze | grep torch
torch==2.0.0+cpu

$ docker run bitnami/pytorch:1-debian-11 pip freeze | grep torch
torch==2.0.0+cpu
```

The latest tag in branch 1 with the correct version is `1.13.1-debian-11-r29`:
```console
$ docker run bitnami/pytorch:1.13.1-debian-11-r29 pip freeze | grep torch
torch==1.13.1+cpu
```

For now, we recommend you use the `1.13.1-debian-11-r29` immutable tag. We will internally review this issue and make the rolling tags for branch 1 point to the correct `1.13.1-debian-11-r29` tag.
