### ISSUE TITLE
zookeeper-exporter is missing

### ISSUE THREAD

**Issue by femiadeyemi** [bitnami/containers#38466]
### Name and Version

bitnami/zookeeper-exporter

### What architecture are you using?

None

### What steps will reproduce the bug?

I can't pull `bitnami/zookeeper-exporter` image from docker. 

### What do you see instead?

The page for the project on docker.io returns 404

**Comment by carrodher** [comment]
We sincerely apologize for the inconvenience caused by the removal of the deprecated container image from DockerHub. We understand that this decision may have disrupted your workflow, and we deeply regret any inconvenience this may have caused.

The bitnami/zookeeper-exporter had not been maintained for several years, and it posed potential security risks due to outdated code and lack of updates. Our top priority is to ensure the security and reliability of our platform, which is why we made the decision to remove some container images from DockerHub.

We understand that you may have relied on the functionality provided by the deprecated software, and we apologize for any disruption this has caused to your work processes. We recommend exploring alternative solutions that are actively maintained and provide the necessary security measures.

Once again, we apologize for any inconvenience caused, and we appreciate your understanding and patience in this matter.
