### ISSUE TITLE
[bitnami/mariadb-galera] Galera Arbitrator docker image

### ISSUE THREAD

**Issue by vvarga007** [bitnami/containers#39291]
### Name and Version

bitnami/mariadb-galera

### What is the problem this feature will solve?

Run [garbd](https://galeracluster.com/library/documentation/arbitrator.html) in a container.

### What is the feature you are proposing to solve the problem?

Create a new container just for garbd, or add garbd binary to the 'bitnami/mariadb-galera' image.

### What alternatives have you considered?

Build my own image.

**Comment by carrodher** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; this process could take some time due to limited resources. In the meantime, we will add the 'on-hold' label to prevent the stale bot from closing this issue.

Unfortunately, contributions to the containers' source code are not possible, which needs to be performed by the Bitnami team.

**Comment by j-oss2023** [comment]
I second this

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
