### ISSUE TITLE
[bitnami/airflow] Create Airflow container with Python 3.10 

### ISSUE THREAD

**Issue by EmilieDel** [bitnami/containers#39869]
I would like to use Airflow with Python 3.10. Could it be possible to build the container with this Python version?

**Comment by EmilieDel** [comment]
Sorry to bother, do you think it is something that can be done ?

**Comment by jotamartos** [comment]
Hi, 

Sorry for the delay here. According to the [Airflow's documentation](https://airflow.apache.org/docs/apache-airflow/2.0.1/installation.html#python-versions-support), Python 3.10 is supported by them. I'll make the necessary changes and confirm that everything works before publishing a new version of the container with this change. 

Thank you for taking the time to create this request.

**Comment by jotamartos** [comment]
Hi again @EmilieDel,

I just quickly checked how this change will affect the catalog and found that Python 3.10 is not supported in Centos 7.x due to [OpenSSL 1.1 is not supported](https://peps.python.org/pep-0644/) in that version of the distro.  In order to not to have that difference in the catalogue depending on the distro, we will keep using Python 3.9 for this solution.

Sorry for the inconvenience.
