### ISSUE TITLE
[bitnami/mysql] Don't --force mysql_upgrade on Mysql

### ISSUE THREAD

**Issue by ithuhaiyang** [bitnami/containers#40253]
### Name and Version

bitnami/mysql  9.10.1 

### What architecture are you using?

None

### What steps will reproduce the bug?

<img width="1053" alt="image" src="https://github.com/bitnami/containers/assets/38413748/370e0c2c-6f94-45df-b436-b5d63f16ff33">

execution of server-side SQL statement 'ALTER  TABLE user MODIFY ssl_type enum （'','ANY','X509'SPECIFIED'）NOT NULL；'failed with error code = 3664, error message = 'Failed to delete SDI 'mysql.user' in tablespace 'mysql''.'.

### What is the expected behavior?

<img width="1078" alt="image" src="https://github.com/bitnami/containers/assets/38413748/8ca4e8ce-6394-43d4-8d40-17851d8ed59d">

Restart for forced update, please turn it off

**Comment by ithuhaiyang** [comment]
debug_execute "${DB_BIN_DIR}/mysql_upgrade" "${args[@]}" || echo "This installation is already upgraded"  

- force Why does the restart fail or has it been upgraded

**Comment by gongomgra** [comment]
Hi @ithuhaiyang,

Thanks for using Bitnami. Can you give us more information on your issue and how to reproduce it?

**Comment by EamonZhang** [comment]
I'm also experiencing this problem, the container keeps restarting and reporting errors

same to https://github.com/bitnami/containers/issues/44854

repair method
https://github.com/bitnami/containers/issues/44854

**Comment by SBANASGH** [comment]
I also encountered this problem, which has troubled me for two days. Here is the reason for my problem:
At first, I was running my mysql service on K8s+NFS, but after running for a while, I don’t know why the Pod could not start normally (the Pod log showed ERROR MY-012960 MY-012930 MY-010334 MY-010020 MY-010119). 
In order to quickly solve the problem, I copied the data in NFS to the docker machine and used --volume to start it in the docker container, which eventually led to this problem.

**Comment by isakuliah** [comment]
I found simple solution in this [thread](https://stackoverflow.com/a/77409199)

sudo systemctl stop mysql
/usr/sbin/mysqld --upgrade=MINIMAL
sudo systemctl start mysql

credit to [durgesh](https://stackoverflow.com/users/7883362/durgesh)

**Comment by ndm10** [comment]
@isakuliah it's really work and helpful, thank you and shout out to [durgesh](https://stackoverflow.com/users/7883362/durgesh)
