### ISSUE TITLE
Airflow volume /opt/bitnami/airflow

### ISSUE THREAD

**Issue by lukasheinz92** [bitnami/containers#42540]
### Name and Version

bitnami/airflow:2.5.2

### What is the problem this feature will solve?

This is rather question than a feature request - is it safe to use the same volume mapped to `/opt/bitnami/airflow` for all three containers (web UI, worker, scheduler)? Currently I use the same volume mapped to `/opt/bitnami/airflow/dags` so I can create and edit dags in a single folder and it works. I want to do the same with the `airflow.cfg` config file so I can edit the config file in one place. It would be great to update this page [https://github.com/bitnami/containers/tree/main/bitnami/airflow](https://github.com/bitnami/containers/tree/main/bitnami/airflow) if using a single volume for `/opt/bitnami/airflow` is possible or not.

### What is the feature you are proposing to solve the problem?

Mapping a single volume to `/opt/bitnami/airflow` for all three containers would simplify the process of working with dags and config file - all would be in one place.

**Comment by FraPazGal** [comment]
Hi @lukasheinz92, I would star by saying I haven't done an in-depth investigation on this but I would say using the same config file for the 3 containers may be viable if you provide the config file already generated. That is because each of the containers will try to generate a config file if it doesn't exist. That said, I wouldn't recommend using the whole same volume for the three containers as conflicts are more likely to occur.

If you make this setup work using a single config file and you want to share your solution, we'll be happy to review any PR adding a new section to our container's README!

**Comment by lukasheinz92** [comment]
Hi @FraPazGal thank you for your answer. I have already tried to create a volume mapped to `/opt/bitnami/airflow` for all the three containers (using a development instance) so the config file, DAGs etc. are shared from one location. I have tested some DAG runs and I haven't encoutered any problems. The question is if any problem may appear in the future because of this setting. I haven't found any answer on this so I am careful to deploy such solution to production. If it's safe then it would be great to mention it here: https://github.com/bitnami/containers/tree/main/bitnami/airflow
