### ISSUE TITLE
[bitnami/kafka] latest update crash

### ISSUE THREAD

**Issue by benitogf** [bitnami/containers#43120]
### Name and Version

bitnami/kafka

### What architecture are you using?

None

### What steps will reproduce the bug?

Using the latest build and this compose file:

```
version: '3.3'
services:
  kafka:
    image: bitnami/kafka:latest
    hostname: 'xtable'
    ports:
      - "9092:9092"
    environment:
      - TZ=Asia/Hong_Kong
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /var/lib/bitnami/kafka:/bitnami/kafka
```

getting: 

> kafka haven't been configured to work in either raft or zookeper mode

and crash

rollback to 3.5.1-debian-11-r3 works

### What is the expected behavior?

work with the same configuration? what changes are needed?

### What do you see instead?

application crash

**Comment by migruiz4** [comment]
Hi @benitogf,

The latest update of the `bitnami/kafka` image requires additional env variables to be deployed.

In order to continue support for both Zookeeper and KRaft modes, the image no longer selects a default mode but has to be configured with some minimum settings depending on the desired mode.

To continue using KRaft mode, please use the following docker-compose:
https://github.com/bitnami/containers/blob/0039bc1c3b1d5f6aaf7d36e3360352ab5a63acbf/bitnami/kafka/docker-compose.yml#L1-L26

I would recommend taking a look at the 'Notable changes' section of the README for more details: https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#351-debian-11-r4-341-debian-11-r50-332-debian-11-r176-and-323-debian-11-r161

**Comment by migruiz4** [comment]
I'm sorry for the inconvenience, but due to our release format being based on the upstream version + image revision we don't have a method to control major releases.

For production environments, we recommend not using rolling tags such as `latest` or `3.5` and instead using immutable tags such as `bitnami/kafka:3.5.1-debian-11-r4`. This will give you better control when upgrading.

**Comment by benitogf** [comment]
Thanks @migruiz4 I liked better the auto Kraft 😄 wonder if it might come back when zookeper support is dropped? or the plan is to keep zookeeper ?

**Comment by dspaeth-breuni** [comment]
I've recently encountered an issue which I believe could be a result of changes made to the bitnami/kafka:3.4 Docker image. Our project uses a pinned version in a Docker-compose file, which ideally should ensure a consistent environment. However, it seems that the image behaves differently now, possibly due to some changes introduced in the image itself.

The situation becomes particularly confusing because the behavior isn't consistent across environments. In our local development setup, the application works perfectly fine due to Docker's image caching. However, when we try to deploy the same setup within our pipeline, it fails.

One potential cause for this could be the introduction of new required environment variables. If this is indeed the case, it would be immensely helpful if an error message could be output stating the need for these new variables.

Introducing breaking changes to an existing Docker image version can be quite disruptive, especially if there's no clear communication or error messages guiding us on how to adjust our configurations.

Could you please provide some insights into this issue? We'd appreciate any assistance on whether any changes have been made that might explain this behavior and how we can update our setup to work with the current state of the image.

Thank you.

**Comment by migruiz4** [comment]
Hi @dspaeth-breuni,

As previously mentioned, for production environments we recommend using immutable tags, such as `bitnami/kafka:3.5.1-debian-11-r7` instead of rolling tags, e.g. `bitnami/kafka:3.5`.
That would ensure the same behavior between environments and better control of updates.

It is difficult to determine the cause of the issue as you haven't shared the error logs, but considering your pipelines would be pulling the latest images, it is possible that the error is caused by the environment variables change.

We have updated the bitnami/kafka [README.md](https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md) as well as the example [docker-compose.yaml](https://github.com/bitnami/containers/blob/main/bitnami/kafka/docker-compose.yml).

In the README.md you can find all the documentation required to deploy your Bitnami Kafka containers, as well as the [Notable changes](https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#351-debian-11-r4-341-debian-11-r50-332-debian-11-r176-and-323-debian-11-r161) section that describe all the changes introduced in the latest release.

**Note**: we are currently facing an issue where the [docker-compose-cluster.yaml](https://github.com/bitnami/containers/blob/main/bitnami/kafka/docker-compose-cluster.yml) has not yet being updated, please do not use that file as reference. For a cluster example please use [this](https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#setting-up-a-apache-kafka-kraft-cluster-with-dedicated-nodes) instead as reference for each node type.

**Comment by migruiz4** [comment]
Hi @erich-ef, 

`bitnami/kafka:3.5.1` is also a rolling tag, immutable tags have the format `bitnami/kafka:3.5.1-debian-11-rX`.

**Comment by chasebenedict1** [comment]
I am getting the same issue as mentioned by other people above:

$ docker run bitnami/kafka:3.5.1-debian-11-r7
kafka 13:59:08.99 
kafka 13:59:08.99 Welcome to the Bitnami kafka container
kafka 13:59:08.99 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 13:59:09.00 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 13:59:09.00
kafka 13:59:09.01 INFO  ==> ** Starting Kafka setup **
kafka 13:59:09.11 ERROR ==> Kafka haven't been configured to work in either Raft or Zookeper mode. Please make sure at least one of the modes is configured.
kafka 13:59:09.12 WARN  ==> Kafka has been configured with a PLAINTEXT listener, this setting is not recommended for production environments.

I pulled an immutable tag like suggested and everything. Not sure what else I could do to make this work.

**Comment by benitogf** [comment]
@chasebenedict1  hey this is the entry I'm running on compose now:

```
  kafka:
    image: bitnami/kafka:3.5.1-debian-11-r3
    hostname: 'bitnami'
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /var/lib/bitnami/kafka:/bitnami/kafka
```

**Comment by migruiz4** [comment]
Hi @benitogf @chasebenedict1,

As I mentioned in my previous comment https://github.com/bitnami/containers/issues/43120#issuecomment-1659833435.

In order to improve compatibility with both Zookeeper mode and KRaft more, the `bitnami/kafka` image now requires additional minimum configuration to run.

**Comment by niemyjski** [comment]
What is the minimal changes to get this to run, upgrading from 3.4.0 to 3.6.1 broke.

**Comment by migruiz4** [comment]
Hi @niemyjski,

I think Kafka 3.6 introduced some breaking changes upstream that affect upgrades, maybe the following guide helps you: https://kafka.apache.org/36/documentation/streams/upgrade-guide
