### ISSUE TITLE
[bitnami/java] Run java as run root user

### ISSUE THREAD

**Issue by baedorf** [bitnami/containers#43211]
### Name and Version

bitnami/java:17

### What is the problem this feature will solve?

According to the documentation, It seems to me that the java app is running as the root user.
This could lead to security problems.

### What is the feature you are proposing to solve the problem?

Please change behaviour to run the java app as a non root user, like in many of your other containers.

**Comment by javsalgar** [comment]
Hi,

The reasoning behind having a `root` user by default is because it is a development container, therefore we want to provide more flexibility for devs to work with the container. If you are using the container for your final application, you can change the user to a non-root one like 1001 just by setting the `user` section in the docker-compose, or the `-u` in docker run.
