### ISSUE TITLE
[bitnami/thanos] looking for v0.28.0

### ISSUE THREAD

**Issue by aslafy-z** [bitnami/containers#4449]
### Name and Version

bitnami/thanos:0.28.0

### What steps will reproduce the bug?

I'm looking for this image but it looks like the image was not built as of today.

### What is the expected behavior?

It should be automatically built?

### What do you see instead?

No updated container defintion.

**Comment by aoterolorenzo** [comment]
Hi @aslafy-z,

Seems that the version [0.28.0-scratch-r0](https://hub.docker.com/layers/bitnami/thanos/0.28.0-scratch-r0/images/sha256-114412a865f6b632d330e109e1364240dc225eff1f74a650ed73889ae0b971b3?context=explore) was released just a day after you filed the issue (#4587). Indeed, the new versions are detected by our system and the release process is automatic unless a specific version would need of manually intervention due to its nature and changes.
