### ISSUE TITLE
[bitnami/keycloak] allow other databeses than postgres

### ISSUE THREAD

**Issue by dafik** [bitnami/containers#4767]
### Name and Version

bitnami/keycloak:18.0.2-debian-11-r26

### What is the problem this feature will solve?

after keycloak was migrate from jboss to quarkus - there are embed other sql drivers

`INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]`

so h2, mariadb, mssql, mysql, oracle, postgresql are supported out of the box.

### What is the feature you are proposing to solve the problem?

there should be variable for setting vendor 

### What alternatives have you considered?

for mssql i'm forced to write/using custom int script:

```
keycloak_configure_database() {
    local jdbc_params
    jdbc_params="$(echo "$KEYCLOAK_JDBC_PARAMS" | sed -E '/^$|^\&.+$/!s/^/\&/;s/\&/\\&/g')"

    info "Configuring database settings"
    keycloak_conf_set "db" "mssql"
    keycloak_conf_set "db-username" "$KEYCLOAK_DATABASE_USER"
    keycloak_conf_set "db-password" "$KEYCLOAK_DATABASE_PASSWORD"
    keycloak_conf_set "db-url" "jdbc:sqlserver://${KEYCLOAK_DATABASE_HOST}:${KEYCLOAK_DATABASE_PORT};databaseName=${KEYCLOAK_DATABASE_NAME}${jdbc_params}"
    keycloak_conf_set "db-schema" "$KEYCLOAK_DATABASE_SCHEMA"
    keycloak_conf_set "transaction-xa-enabled" "false"
}

info "custom init"

keycloak_configure_database
```

**Comment by jotamartos** [comment]
Hi @dafik,

Thank you for your interest and for taking the time to let us know about this. We are aware of the different SQL drivers the solution supports. However, adding support to all of them in the configuration scripts will make the solution more error-prone. Please note that we can't test all the corner cases and prefer to keep it simple for anyone to deploy and test it. 

In your case, if you need a different configuration, the init scripts is a valid solution. That's why we added support for those scripts. In case more users request this feature in the future, we will evaluate it and decide if we can implement it. For now, we will keep it as it is to avoid errors during the deployment. 

Thank you for your feedback!

**Comment by polaris940** [comment]
+1 on this. Would love it if the chart supported all the database options of the app. 

Another way to accomplish this might be to ease the validation on either needing the `postgresql.enabled` or `externalDatabase` config to allow for setting the variables manually through the environment variables (`extraEnvVars`/`extraEnvVarsSecret`), which are supported by the app. 

Ideally, though, the `externalDatabase` config should mirror/passthrough the environment variables offered by the app (`KC_DB_*`). 

https://www.keycloak.org/server/all-config

Haven't yet found the combination to let my setup use the `KC_DB_URL` I have configured without complaining about the database values not being set or getting overridden by the ones that the chart sets up when those configs are defined in order to pass the validation. 

```
Error: Error: execution error at (keycloak/templates/NOTES.txt:95:4):  
VALUES VALIDATION:  
keycloak: database  
    You disabled the PostgreSQL sub-chart but did not specify an external PostgreSQL host.  
    Either deploy the PostgreSQL sub-chart (--set postgresql.enabled=true),  
    or set a value for the external database host (--set externalDatabase.host=FOO)  
    or set a value for the external database existing secret (--set externalDatabase.existingSecret=BAR).
```

**Comment by jotamartos** [comment]
Hi @polaris940,

Sorry for the delay here. You should be able to apply @dafik's suggestion by following the Keycloak's Chart documentation here: 

https://github.com/bitnami/charts/tree/master/bitnami/keycloak#initialize-a-fresh-instance

Thanks!
