### ISSUE TITLE
[bitnami/mediawiki] Some plugins can't work from /bitnami/mediawiki

### ISSUE THREAD

**Issue by jakubgs** [bitnami/containers#48162]
### Name and Version

bitnami/mediawiki:1.40.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Attempt to install a plugin like `BlueSpiceGroupManager`.
2. Mount the extension under `/bitnami/mediawiki/extensions` as expeted.
3. Start the application and see errors like this:
    ```
    PHP Warning: require_once(/bitnami/mediawiki/maintenance/Maintenance.php):
      Failed to open stream: No such file or directory
    ```
4. Attempt to mount the extension under `/opt/bitnami/mediawki/extensions`.
5. See failure to delete files from that folder at startup:
    ```
    rm: cannot remove '/opt/bitnami/mediawiki/extensions/BlueSpiceGroupManager/.gitignore': Permission denied
    ```

### What is the expected behavior?

How exactly am i expected to install an extension that expects `/bitnami/mediawiki/maintenance` to exist when it's actually under `/opt/bitnami/mediawiki/maintenance` and I cannot mount the extension there because it will be removed.

### What do you see instead?

Chaos.

**Comment by juan131** [comment]
Hi @jakubgs 

Mediawiki source files are located under `/opt/bitnami/mediawiki`. That said, there are a series of subdirectories that are "persisted" to avoid losing your data if the container restarts.

For instance, as you can see in the command below, the `extensions` & `images` directories are actually symlinks to subdirectories under `/bitnami/mediawiki` (the directory [where the volumes to persist data are mounted](https://github.com/bitnami/containers/blob/main/bitnami/mediawiki/docker-compose.yml#L27-L28)).

```console
$ ls -la /opt/bitnami/mediawiki
(...)
lrwxrwxrwx  1   1001 root      29 Sep 12 09:44 extensions -> /bitnami/mediawiki/extensions
lrwxrwxrwx  1   1001 root      25 Sep 12 09:44 images -> /bitnami/mediawiki/images
```

These symlinks are created during the 1st initialization on a "clean" environment (no data from previous deployments). You can double-check it by inspecting the container logs:

```console
mediawiki-mediawiki-1  | mediawiki 09:44:45.95 INFO  ==> Persisting MediaWiki installation
mediawiki-mediawiki-1  | mediawiki 09:44:47.47 INFO  ==> ** MediaWiki setup finished! **
```

Therefore, It's recommended that you add your custom extensions after the 1st initialization is completed.

Please also note that Mediawiki runs with a non-root user by default (finde more info at [#why-use-a-non-root-container](https://github.com/bitnami/containers/tree/main/bitnami/mediawiki#why-use-a-non-root-container)), therefore it's very important that the extensions you mount have the right permissions set.

**Comment by jakubgs** [comment]
I understand all of that, none of what you said actually solves the issue.

The issue is that many extensions reference files like `maintenance.php` in a relative manner, so if they are mounted at `/bitnami/mediawiki` they lok for that file there and not under `/opt/bitnami/mediawiki`. That makes no sense.

I have hacked around this by force-creating a symlink from `/bitnami/mediawiki/maintenance` to `/opt/bitnami/mediawiki/maintenance`. It's not pretty, but it works. And honestly, I don't get why those setup scripts are also trying to remove files when they are being mounted under `/opt`.

**Comment by juan131** [comment]
Hi @jakubgs 

You're right! You need symlinks since Mediawiki (and their extensions) use relative paths so it's expected that the whole application is under the same directory.

The reason why we move "data to be persisted" to `/bitnami/mediawiki` and use symlinks is simple: supporting app updates by replacing the container with a new version. How does this work? Simple: if you stop/delete your Mediawiki container all your data is safe since it's in the persistent volume, therefore you can start again the container but updating the container image version (which contains and updated version of Mediawiki, Apache, PHP, etc. under `/opt/bitnami`) and you don't lose your old data since you'll be mounting the same volume.

**Comment by jakubgs** [comment]
But extensions aren't "data to be persisted", they can be always re-downloaded and installed in the `extensions` folder again. None of what you have said actually justifies putting `extensions` in a folder where they will not work unless you create a hack-fix by force-creating a symlink to `maintenance` folder(and/or others?) to allow them to work.

You have 3 options:

1. Stop putting `extensions` volume/folder in a location where some extensions don't work.
2. Create a symlink to `maintenance` in advance and explain why it exists and why it has to exist in a `README`.
3. Leave things as they are but indicate clearly to the user why his extensions might not work and what has to be done.

I really don't think this design decision makes any sense.

**Comment by juan131** [comment]
Hi @jakubgs 

Thank you for your feedback.

I agree extensions are sth that you can reinstall with no major issues. That said, they can be considered data to be persisted since (as a developer) you'll expect the extensions that you installed to while customizing your wiki to exist even if your container is recreated (for whatever reason).

There's a way to modify "what to persist" by the way. As you can see below, there's an environment variable named `MEDIAWIKI_DATA_TO_PERSIST` that indicates the files/directories to be persisted:

- [mediawiki-env.sh#L78](https://github.com/bitnami/containers/blob/main/bitnami/mediawiki/1/debian-11/rootfs/opt/bitnami/scripts/mediawiki-env.sh#L78)

You could overwrite its default value and remove `extensions` from there.

**Comment by jakubgs** [comment]
So will removing `extensions` from `MEDIAWIKI_DATA_TO_PERSIST` prevent the files from being removed if I mount extensions directly under `/opt/bitnami/mediawiki/extensions`?

**Comment by juan131** [comment]
If you apply the changes below in the default docker compose:

```diff
diff --git a/bitnami/mediawiki/docker-compose.yml b/bitnami/mediawiki/docker-compose.yml
index 3e3e1bc4223..2dbb75e119e 100644
--- a/bitnami/mediawiki/docker-compose.yml
+++ b/bitnami/mediawiki/docker-compose.yml
@@ -22,6 +22,7 @@ services:
       - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
       - MEDIAWIKI_DATABASE_USER=bn_mediawiki
       - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
+      - MEDIAWIKI_DATA_TO_PERSIST=images skins LocalSettings.php
       # ALLOW_EMPTY_PASSWORD is recommended only for development.
       - ALLOW_EMPTY_PASSWORD=yes
     volumes:
```

You'll notice that no symlinks will be created for `extensions` and the folder is at `/opt/bitnami/mediawiki/extensions`:

```console
$ docker-compose up -d
$ docker-compose exec mediawiki ls -la /opt/bitnami/mediawiki
total 1976
drwxrwxr-x  1 daemon root    4096 Sep 14 13:18 .
drwxrwxr-x  1 root   root    4096 Sep  9 20:34 ..
(...)
lrwxrwxrwx  1   1001 root      36 Sep 14 13:18 LocalSettings.php -> /bitnami/mediawiki/LocalSettings.php
(...)
drwxrwxr-x 34 daemon root    4096 Aug 18 22:55 extensions
lrwxrwxrwx  1   1001 root      25 Sep 14 13:18 images -> /bitnami/mediawiki/images
(...)
```

That said, whatever changes you do under this folder will be lost if the container gets recreated.
