### ISSUE TITLE
[bitnami/kafka] Healthcheck fails when container is in swarm mode

### ISSUE THREAD

**Issue by MacCracken** [bitnami/containers#50306]
### Name and Version

bitnami/kafka:3.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1.  Running Docker in Swarm mode
2.  kafka service in compose & env file

```dockerfile
services:
  kafka:
     image: bitnami/kafka:3.5.1
      env_file: env/kafka.env
     volumes:
        - kafka:/bitnami/kafka   
      networks:
        - backend
      labels:
        container.service.name: kafka
      healthcheck:
         test: "kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1"
         start_period: 120s
         interval: 10s
         timeout: 5s
         retries: 10
      deploy:
        endpoint_mode: dnsrr
        mode: "replicated"
        replicas: 1

volumes:
  kafka:
``` 

```shell
# KRaft settings
KAFKA_KRAFT_CLUSTER_ID=ACLUSTERIDHERE
KAFKA_CFG_NODE_ID=0
KAFKA_CFG_PROCESS_ROLES=controller,broker
KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
# Listeners
KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
BITNAMI_DEBUG=TRUE
``` 

4.  Starting up the stack including kafka works with healtcheck commented out.
5.  Remove comments from healtcheck and update service
6.  Regardless of start_period, healtcheck attempts to create a health-broker and below error is encountered

Is there specific way to setup kafka healtchecks on swarm?  As this error does not appear when doing the same healtcheck for a single server compose up.

### What is the expected behavior?

Within a Docker Swarm cluster, the container does not to fail upon initialization of process when healtcheck in compose file is enabled.

### What do you see instead?

Error displayed shortly after startup on container in swarm with any type of healtcheck.

```java
[2023-09-26 18:04:36,695] INFO [broker-0-to-controller-heartbeat-channel-manager]: Recorded new controller, from now on will use node kafka:9093 (id: 0 rack: null) (kafka.server.BrokerToControllerRequestThread)
[2023-09-26 18:04:36,696] WARN [BrokerToControllerChannelManager id=0 name=heartbeat] Error connecting to node kafka:9093 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: kafka
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:510)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
        at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1030)
        at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1(InterBrokerSendThread.scala:107)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1$adapted(InterBrokerSendThread.scala:103)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at kafka.common.InterBrokerSendThread.sendRequests(InterBrokerSendThread.scala:103)
        at kafka.common.InterBrokerSendThread.pollOnce(InterBrokerSendThread.scala:77)
        at kafka.server.BrokerToControllerRequestThread.doWork(BrokerToControllerChannelManager.scala:418)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:127)
```

**Comment by javsalgar** [comment]
Hi,

I'm afraid this has to do more with your configuration of the app rather than an issue of the Bitnami packaging of Kafka. My advice would be to check our Bitnami chart for kafka for the healthchecks we perform.

**Comment by MacCracken** [comment]
Hello  Javier (@javsalgar),

Could you provide some examples as I've scoured the interwebs and reviewed charts, unless I'm missing something I have not come across healtcheck examples.  I've seem couple different test string examples but nothing seems to work when running with Kafka on a Swarm cluster.

**Comment by javsalgar** [comment]
This is what we currently have in the Bitnami Kafka helm chart:

```
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.broker.livenessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: "client"

```

In this case, we perform a test at the socket level (I recall that other tests were adding too much noise in the logs)

**Comment by jonathan-dev** [comment]
I think I am experiencing the same problem as @MacCracken or at least I am getting the same symptoms. With no health check it works like normal and with adding one I get the `java.net.UnknownHostException: kafka`. Even when using a healthcheck like: `echo test` (which shouldn't be a problem at all). Did you figure out the problem or whats going on here? Thanks

**Comment by johnpitchko** [comment]
Hello, I believe that I am also encountering the same `Error connecting to node kafka:9093` error on Amazon ECS. However, I do not have the healthcheck enabled. @MacCracken or @jonathan-dev can you gleam any light on this? Assume that this is a config issue in the ECS task definition.

**Comment by zivisraelyankelevitz** [comment]
the issue is still reproducable with the bitnami/kafka:3.6.2-debian-12-r12
no matter which comand is used in the healthcheack kafka container fails to start
i'm using kraft mode
even a simple test against the open port does not work. for example:

 healthcheck:
      start_period: 60s  # Start after 1 minute
      interval: 60s       # Check every 60 seconds
      retries: 5
      timeout: 15s
      test: ["CMD-SHELL", "timeout 5 bash -c 'echo > /dev/tcp/kafka/9092'"]


also, trying to run any relevant kafka script inside the /opt/bitnami/kafka/bin folder fails.
for example:

healthcheck:
      start_period: 60s  # Start after 1 minute
      interval: 60s       # Check every 60 seconds
      retries: 5
      timeout: 15s
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka:9092"]


the container repeat this log error, again and again:

| [2025-03-25 13:07:57,407] WARN [BrokerToControllerChannelManager id=101 name=heartbeat] Error connecting to node kafka:9093 (id: 101 rack: null) (org.apache.kafka.clients.NetworkClient)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    | java.net.UnknownHostException: kafka
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:122)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.resolveAddresses(ClusterConnectionStates.java:537)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:512)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1030)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at org.apache.kafka.server.util.InterBrokerSendThread.sendRequests(InterBrokerSendThread.java:145)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at org.apache.kafka.server.util.InterBrokerSendThread.pollOnce(InterBrokerSendThread.java:108)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at kafka.server.BrokerToControllerRequestThread.doWork(BrokerToControllerChannelManager.scala:421)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    |  at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:130)
gnss_kafka.1.7381eriyfpzz@gdn-vs-sync3-alma810-53.advaoptical.com    | [2025-03-25 13:07:57,457] INFO [broker-101-to-controller-heartbeat-channel-manager]: Recorded new controller, from now on will use node kafka:9093 (id: 101 rack: null) (kafka.server.BrokerToControllerRequestThread)
