### ISSUE TITLE
[bitnami/jmx-exporter] New release not available

### ISSUE THREAD

**Issue by harpaj** [bitnami/containers#52045]
### Name and Version

bitnami/jmx-exporter:0.19.0

### What is the problem this feature will solve?

Version 0.20.0 of the Prometheus JMX Exporter was released in August: https://github.com/prometheus/jmx_exporter/releases/tag/0.20.0

However, Bitnami images are not yet available.

### What is the feature you are proposing to solve the problem?

Find the issue and make the 0.20.0 image available.

### What alternatives have you considered?

I'm happy to help out with a PR but it seems that this system is not open to the public

**Comment by carrodher** [comment]
Thanks for letting us know. Our automated tool didn't detect the new version because the upstream source code tarball changed its name:
- https://github.com/prometheus/jmx_exporter/archive/refs/tags/parent-0.19.0.zip
VS
- https://github.com/prometheus/jmx_exporter/archive/refs/tags/0.20.0.zip

so the regex we were using didn't work for this new version.

I just created an internal task to check the download URL and release the new version. We'll update this thread once ready.

**Comment by gongomgra** [comment]
Hi @harpaj,

Just a quick note to let you know that we have just released `bitnami/jmx-exporter:0.20.0-debian-11-r0` image for jmx-exporter version `0.20.0`.

**Comment by harpaj** [comment]
Awesome, thank's a lot for the quick reaction!
