### ISSUE TITLE
Criticals Found in docker.io/bitnami/redis:7.2.1-debian-11-r0

### ISSUE THREAD

**Issue by koenigfa1** [bitnami/containers#52216]
### Name and Version

bitnami/redis:7.2.1-debian-11-r0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

- Using this helm Chart in K8s Cluster: https://artifacthub.io/packages/helm/bitnami/redis/18.1.2
- Using Image docker.io/bitnami/redis:7.2.1-debian-11-r0 as it set in the helm Chart.
- Got  2 Criticals: **trivy image docker.io/bitnami/redis:7.2.1-debian-11-r0**

### What is the expected behavior?

No Criticals. I need to run this Redis Version Helm Chart in my Cluster with an image which has no criticals. What is the best way to do that? Thank you very much!

### What do you see instead?

With **trivy image docker.io/bitnami/redis:7.2.1-debian-11-r0** i get 2 Criticals:

CVE-2023-45853
CVE-2019-8457 

### Additional information

Using the VMware Application Catalog is not an option.

**Comment by carrodher** [comment]
I understand your concern regarding security vulnerabilities. While we regularly update our images with the latest system packages, certain CVEs may persist until they are patched in either the OS or the application. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

When running the scanner with the `--ignore-unfixed` flag you will see only those CVEs with a fixable version. In the same way, please note the latest version of the Helm chart is using Redis 7.2.2 instead of 7.2.1, and running the scanner with that version this is the result:
```console
$ trivy image --ignore-unfixed docker.io/bitnami/redis:7.2.2-debian-11-r0
2023-10-30T09:07:52.210+0100	INFO	Vulnerability scanning is enabled
2023-10-30T09:07:52.210+0100	INFO	Secret scanning is enabled
2023-10-30T09:07:52.210+0100	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-10-30T09:07:52.210+0100	INFO	Please see also https://aquasecurity.github.io/trivy/v0.46/docs/scanner/secret/#recommendation for faster secret detection
2023-10-30T09:07:55.819+0100	INFO	Detected OS: debian
2023-10-30T09:07:55.819+0100	INFO	Detecting Debian vulnerabilities...
2023-10-30T09:07:55.826+0100	INFO	Number of language-specific files: 3
2023-10-30T09:07:55.826+0100	INFO	Detecting bitnami vulnerabilities...
2023-10-30T09:07:55.826+0100	INFO	Detecting gobinary vulnerabilities...

docker.io/bitnami/redis:7.2.2-debian-11-r0 (debian 11.8)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)


opt/bitnami/redis (bitnami)

Total: 1 (UNKNOWN: 0, LOW: 1, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

┌─────────┬───────────────┬──────────┬────────┬───────────────────┬────────────────┬───────────────────────────────────────────┐
│ Library │ Vulnerability │ Severity │ Status │ Installed Version │ Fixed Version  │                   Title                   │
├─────────┼───────────────┼──────────┼────────┼───────────────────┼────────────────┼───────────────────────────────────────────┤
│ redis   │ CVE-2022-3647 │ LOW      │ fixed  │ 7.2.2             │ 2022-09-29.0.0 │ crash in sigsegvHandler debug function    │
│         │               │          │        │                   │                │ https://avd.aquasec.com/nvd/cve-2022-3647 │
└─────────┴───────────────┴──────────┴────────┴───────────────────┴────────────────┴───────────────────────────────────────────┘
```

The Bitnami Application Catalog (OpenSource) is built on Debian 11. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 10, 11 & 12, PhotonOS 3 & 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

If you have any further questions, feel free to ask.
