### ISSUE TITLE
[openldap] build with libargon2-dev to enable ARGON2 password scheme

### ISSUE THREAD

**Issue by gutmensch** [bitnami/containers#5508]
### Name and Version

bitnami/openldap:2.6.3

### What is the problem this feature will solve?

Enable (by now) standard password scheme ARGON2 to be used for binding.

### What is the feature you are proposing to solve the problem?

During install before build
```
apt install libargon2-dev
```

During openldap configure before build
```
./configure --with-argon2 ...
```

As runtime dependency
```
apt install libargon2-1
```

### What alternatives have you considered?

Other password hashes work of course, but [Argon2](https://github.com/P-H-C/phc-winner-argon2/blob/master/argon2-specs.pdf#section.9) is supported almost everywhere now and is theoretically advanced compared to the others.

**Comment by carrodher** [comment]
Thanks for the suggestion. There were some tickets in the past asking for the same feature, see https://github.com/bitnami/bitnami-docker-openldap/issues/79 and https://github.com/bitnami/bitnami-docker-openldap/issues/99.
As a result of those tickets, we created an internal task to evaluate and implement (if needed) this feature, unfortunately, due to the team capacity and other priorities, the internal task is still in our backlog.

I will move this issue to `On hold` and we will update it once we have more news

**Comment by gongomgra** [comment]
Hi @gutmensch, @jar349, @Shihta, @binaryape,

Thanks for your interest in using Bitnami. We have just released a new version of our OpenLDAP containers adding support for the Argon2 and PBKDF2 hashing algorithms. Please find below the specific tags of the latest containers:

* OpenLDAP 2.5: `2.5.13-debian-11-r53`.
* OpenLDAP 2.6: `2.6.3-debian-11-r49`.

Hope it helps!
