### ISSUE TITLE
Valkey BItnami Container

### ISSUE THREAD

**Issue by nerdeveloper** [bitnami/containers#65181]
### Name and Version

NIL

### What is the problem this feature will solve?

With the new Redis license, it will be great to have a BItnami container for new releases for the Redis fork, Valkey. Here is the link: https://github.com/valkey-io/valkey

### What is the feature you are proposing to solve the problem?

This allows existing users to maintain the same code base and switch providers from Redis to Valkey

**Comment by williejay2017** [comment]
Can we get alpine versions of bitnami valkey? The Debian version currently offered has CVEs (OpenSSL and bookworm). Valkey has a clean alpine image version of Valkey but they don't have a chart and refer to bitnami for charts. I have some capacity to try and create a chart off their docker image but was wondering if you guys could publish an alpine version of your valkey image so I can swap and drop hahaha. Thanks.

**Comment by carrodher** [comment]
I understand your concern regarding security vulnerabilities. We regularly update our images with the latest system packages; however, certain CVEs may persist until they are patched in the OS or application. Additionally, some CVEs remain unfixed due to the absence of available patches. In vulnerability scanners like Trivy, you can use the `--ignore-unfixed` flag to ignore such CVEs. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

The Bitnami Application Catalog (OpenSource) is built on Debian 12. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 11 & 12, PhotonOS 4 & 5, Ubuntu 22.04 & 24.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

If you have any further questions, feel free to ask.
