### ISSUE TITLE
[Odoo17] Impossible to list and access to addons directory

### ISSUE THREAD

**Issue by sergueikp** [bitnami/containers#65724]
### Describe your issue as much as you can

Hello, 
I'm using docker image container.
How to see all addons folders inside /opt/bitnami/odoo/addons ? How to make it persistent and have a copy of it on local machine?

**Comment by jotamartos** [comment]
I just transfer your issue to the https://github.com/bitnami/containers repository as this is a containers-related question. 

The addons directory is already being persisted when launching the container 

https://github.com/bitnami/containers/blob/main/bitnami/odoo/17/debian-12/rootfs/opt/bitnami/scripts/odoo-env.sh#L86

If you want to have it locally, you can mount a local directory when launching the container instead of mounting a volume 

https://github.com/bitnami/containers/blob/main/bitnami/odoo/docker-compose.yml
