### ISSUE TITLE
Impossible to see addons in odoo17 container 

### ISSUE THREAD

**Issue by sergueikp** [bitnami/containers#65764]
### Name and Version

bitnami/odoo:17.0.20240405

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We are trying bitnami/odoo:17.0.20240405 image. 
We made container data persistent.
We have the persistence folder on our local host created like this in the _docker-compose.yml_ file:
``` 
- /home/serguei/docker_persistance/bitnami/odoo:/bitnami/odoo
```
Impossible to see addons in the odoo addons folder. We need to access to addons folder! 
The addons folder is empty on the local machine. 

### What is the expected behavior?

We must see all modules inside addons folder of the container.

### What do you see instead?

The addons folder is empty.
The only file that is visible is odoo.conf

**Comment by sergueikp** [comment]
Below docker-compose.yml persistance for Odoo files.
Folders /addons and /python3.11  are empty. 

They must have other folders inside them. 

odoo:
    image: docker.io/bitnami/odoo:17.0.20240405
    container_name: odoo17
    networks:
      - odoo17-network
    restart: always
    ports:
      - '80:8069'
    volumes:
      - /home/serguei/docker_persistance/bitnami/odoo:/bitnami/odoo
      - /home/serguei/docker_persistance/opt/bitnami/odoo/odoo/addons:/opt/bitnami/odoo/odoo/addons
      - /home/serguei/docker_persistance/opt/bitnami/python/lib/python3.11/:/opt/bitnami/python/lib/python3.11

**Comment by juan131** [comment]
Hi @sergueikp 

I launched Odoo using the [docker-compose.yaml](https://github.com/bitnami/containers/blob/main/bitnami/odoo/docker-compose.yml) included on this repository (without any modification to mount host directories instead of using docker volumes).

Once the containers were ready...

```console
$ docker compose ps
NAME                IMAGE                             COMMAND                  SERVICE      CREATED         STATUS         PORTS
odoo-odoo-1         docker.io/bitnami/odoo:17         "/opt/bitnami/script…"   odoo         4 minutes ago   Up 4 minutes   3000/tcp, 8072/tcp, 0.0.0.0:80->8069/tcp
odoo-postgresql-1   docker.io/bitnami/postgresql:16   "/opt/bitnami/script…"   postgresql   4 minutes ago   Up 4 minutes   5432/tcp
```

... I accessed the Odoo container and, as you can see below, the `/opt/bitnami/odoo/addons` folder is a symbolic link to `/bitnami/odoo/addons`, where addons are persisted given a volume is mounted at `/bitnami/odoo`.

```console
$ docker compose exec odoo bash
root@869f4a70e546:/# ls -la /opt/bitnami/odoo/
total 212
drwxr-xr-x  1 odoo root   4096 May  2 06:55 .
drwxrwxr-x  1 root root   4096 Apr 23 14:42 ..
-rw-r--r--  1 root root 150025 Apr  5 07:23 .spdx-odoo.spdx
lrwxrwxrwx  1 root root     20 May  2 06:55 addons -> /bitnami/odoo/addons
drwxr-xr-x  2 root root   4096 Apr 23 14:42 bin
lrwxrwxrwx  1 root root     18 May  2 06:55 conf -> /bitnami/odoo/conf
lrwxrwxrwx  1 root root     18 May  2 06:55 data -> /bitnami/odoo/data
drwxr-xr-x  3 root root   4096 Apr  5 06:51 lib
drwxr-xr-x  2 root root   4096 Apr  5 06:51 licenses
drwxrwxr-x  2 odoo root   4096 Apr 23 14:42 log
drwxr-xr-x 26 root root   4096 Apr  5 06:51 node_modules
drwxr-xr-x  2 root root   4096 Apr 23 14:42 odoo
-rw-r--r--  1 root root   9081 Apr  5 06:17 package-lock.json
-rw-r--r--  1 root root     88 Apr  5 06:17 package.json
drwxrwxr-x  1 odoo root   4096 May  2 06:55 tmp
drwxr-xr-x  5 root root   4096 Apr  5 06:51 venv
```

By default, the directory is empty but once you install new addons (e.g. using Odoo UI) you should see them there.

Find more information about persistence mounting host directories on [this link](https://github.com/bitnami/containers/tree/main/bitnami/odoo#mount-host-directories-as-data-volumes-with-docker-compose).
