### ISSUE TITLE
[bitnami/postgresql] Support for PL/Tcl; PL/Perl and PL/Python

### ISSUE THREAD

**Issue by remcoboerma** [bitnami/containers#6632]
### Name and Version

bitnami-docker-postgresql

### What is the problem this feature will solve?

Postgresql officially supports serveral procedural languages. The bitnami image doesn't include those. 

See [previous issue](https://github.com/bitnami/bitnami-docker-postgresql/issues/252).

### What is the feature you are proposing to solve the problem?

Please support major procedural languages that are [documented officially upstream](https://www.postgresql.org/docs/current/server-programming.html), namely:

PL/Tcl
PL/Perl
PL/Python (python3u should be enough since Python 2 is EOL'd)

### What alternatives have you considered?

Using other images; keeping more code in the application layer instead of the database. But that can be a hassle at times.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. Right now we are being very conservative in adding these extensions because of the risks in size increase and vulnerability surface. Adding TCL, Perl and Python will likely increase the amount of CVEs and the container size.

I will leave this ticket open so we can consider it in the future if more users demand it.
