### ISSUE TITLE
[ bitnami/gitea ] how to handle all env variables

### ISSUE THREAD

**Issue by w0aw** [bitnami/containers#67357]
### Name and Version

bitnami/gitea:latest

### What is the problem this feature will solve?

this is not a feature req. it's more of a question. -

in official [Gitea docs](https://docs.gitea.com/administration/config-cheat-sheet) we can configure env variables like `GITEA__SECTION_NAME__KEY_NAME`. I know in bitnami/gitea chart we can provide env variables the same way but... there is some difference and even in readme file it's not defined how to use the rest of the env variables, for eg. 

1. difference - GITEA__mailer__PASSWD (official) & GITEA_SMTP_PASSWORD (bitnami) 
2. in official we have GITEA__mailer__PASSWD__FILE or GITEA__cache__HOST &even many more envVars. ([source](https://docs.gitea.com/installation/install-with-docker-rootless#managing-deployments-with-environment-variables))

We can use the app.ini file for config.....

but the question is can we use official gitea env variables in bitnami images?? if yes then we should put a note in bitnami/gitea's readme file about the rest of the env variables.

thank you

### What is the feature you are proposing to solve the problem?

I guess nobody wants to expose secrets like redis pass and many more inside the app.ini file

### What alternatives have you considered?

if official env variables are not supported, we should provide a way to define all env variables. eg. `GITEA_$sectionName_$keyName` and `GITEA_$sectionName_$keyName_$file`

**Comment by rafariossaa** [comment]
Hi,
  Short answer is yes, you can use gitea's environment variables. 
  Any environment variable you set when launching the image are going to be available inside the running container, so if the process honor those, they should produce the desired effect.
  The bitnami's environment variables are there because they are handled by the initialization scripts, for example [here](https://github.com/bitnami/containers/blob/4a7d93840131d7fdcce090c7c64baf138d0dd7cb/bitnami/gitea/1/debian-12/rootfs/opt/bitnami/scripts/libgitea.sh#L217), in this case they are used to generate settings in the configuration file.

**Comment by w0aw** [comment]
@rafariossaa thank you. actually i got it working.

closing issue.
