### ISSUE TITLE
bitnami/keycloak upgrade to v 25

### ISSUE THREAD

**Issue by osama-mahmoud-h** [bitnami/containers#69172]
### Name and Version

bitnami/keycloak:25.0.0

### What is the problem this feature will solve?

upgrade bitnami/keycloak docker image to  v:25 / latest versions of keycloak

### What is the feature you are proposing to solve the problem?

Latest features from keycloak and fixes.

### What alternatives have you considered?

using native keycloak from quay.io

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible.

We will close this issue since there is an already existing ticket for this topic, see https://github.com/bitnami/containers/issues/67751
