### ISSUE TITLE
RabbitUI does not work in IPv6

### ISSUE THREAD

**Issue by SpeedyGonzaless** [bitnami/containers#69256]
### Name and Version

bitnami/rabbitmq:3.13.4

### What architecture are you using?

None

### What steps will reproduce the bug?

Run rabbitmq in k8s with IPv6 only network and use ingress.

### What is the expected behavior?

UI is available with DNS mentioned in ingress for rabbitmq

### What do you see instead?

503 Service Temporarily Unavailable

### Additional information

I can see in the repo that UI works only on IPv4
https://github.com/bitnami/containers/blob/main/bitnami/rabbitmq/3.13/debian-12/rootfs/opt/bitnami/scripts/librabbitmq.sh#L129C1-L129C64

Is there any reason for this? And is it possible to make an improvement so that UI will be available in IPv6?

**Comment by jotamartos** [comment]
I think that's probably due to we didn't validate IPv6 in the past. RabbitMQ seems to work with IPv6 according to the documentation

https://www.rabbitmq.com/docs/networking#dual-stack

We now have 2 more functions to validate IPv6 (validate_ipv6) and validate any IP (validate_ip, no matter if v4 or v6)

https://github.com/bitnami/containers/blob/main/bitnami/rabbitmq/3.13/debian-12/prebuildfs/opt/bitnami/scripts/libvalidations.sh#L236

Would you like to make the necessary changes in the code and contribute so everyone benefits from this change? You can follow [our contributing guidelines](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md).

**Comment by SpeedyGonzaless** [comment]
@jotamartos sure
https://github.com/bitnami/containers/pull/69439
