### ISSUE TITLE
[bitnami/openldap] The environment variables for Sync consumer (Syncrepl )

### ISSUE THREAD

**Issue by lihato** [bitnami/containers#69424]
### Name and Version

bitnami/openldap2.6.8

### What is the problem this feature will solve?

About the Replication 
The provider can be specified in the environment variable LDAP_ENABLE_SYNCPROV to enenled
But
Without the consumer's configuration(Syncrepl ), the Replication function can't to used.
Now In the on premise environment, the direction of replication is one direction.
So I wish to make the environment variable for Syncrepl .

### What is the feature you are proposing to solve the problem?

 Add the environment variable LDAP_SYNCREPL

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward this to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will take a look.

**Comment by lihato** [comment]
Thank you for your reply.
Now I have known the infomation.

**Comment by rohan-97** [comment]
Hi All,

Is there any update or any workaround present for configuring consumer client?

As bitnami openldap runs inside an container, 
and containers are ephemeral in nature.
There are high chances for a container to crash.

Syncrepl seems like an important feature so that we can implement highly available LDAP.
