### ISSUE TITLE
[bitnami/kaniko] Kaniko image bitnami/kaniko:1.23.2-debian-12-r2 is tagged with "debian", but built from Scratch

### ISSUE THREAD

**Issue by damoshushu** [bitnami/containers#70019]
### Name and Version

bitnami/kaniko:1.23.2-debian-12-r2

### What architecture are you using?

None

### What steps will reproduce the bug?

https://github.com/bitnami/containers/blob/main/bitnami/kaniko/1/debian-12/Dockerfile#L34

### What is the expected behavior?

this image should based on Debian

### What do you see instead?

I see it is not based on debian
```console
$ docker run -it --entrypoint="" bitnami/kaniko:1.23.2-debian-12-r2 bash
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container:
```

**Comment by carrodher** [comment]
I understand your concern, indeed, the resulting container is not debian-12 but a multi-stage distroless image. The reasoning behind this tagging approach is for naming consistency since we are using debian-12-compiled binaries (i.e https://github.com/bitnami/containers/blob/main/bitnami/kaniko/1/debian-12/Dockerfile#L16-L27).
In the end, we are building distroless images based on Debian, but that does not mean those images contain an underlying Debian OS.
