### ISSUE TITLE
 [bitnami/postgresql-repmgr] Barman integration

### ISSUE THREAD

**Issue by mhkarimi1383** [bitnami/containers#70878]
### Name and Version

bitnami/postgresql-repmgr:16.4.0-debian-12-r0

### What is the problem this feature will solve?

PITR database backup and using wal backups for replication (Since newer versions of repmgr added support for this one) 

I can Help with that since I have used barman a lot 

### What is the feature you are proposing to solve the problem?

installing barman (also barman cloud) on repmgr image. And run backup commands based on envs (aws info, full backup schedule, etc.) on PRIMARY node

### What alternatives have you considered?

Using barman in another container (only usable for backups)

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! In principle we try to be conversative with the amount of plugins, extensions and extra software we include in the container because of size and attack surface reasons. If we see a clear demand from the community, we could consider evaluating, but at the moment try to avoid increasing the image size.

**Comment by mhkarimi1383** [comment]
I think backup and availability of WALs are important in PostgreSQL replication, so I think this is a needed thing
