### ISSUE TITLE
Bitnami volsync helm chart

### ISSUE THREAD

**Issue by viju2008** [bitnami/containers#71492]
### Name and Version

bitnami/volsync

### What is the problem this feature will solve?

Having a Helm chart will help to easily deploy and configure volsync for cross-cluster replication of PV Data

https://artifacthub.io/packages/helm/backube-helm-charts/volsync

### What is the feature you are proposing to solve the problem?

The helm  chart will make it easy to deploy and  configure replication with volsync

**Comment by carrodher** [comment]
Thanks for your suggestion! Unfortunately after an internal review, and due to other priorities, this solution was not considered to be added to the catalog as a Helm chart in the short/mid-term. As a workaround, you can create your Helm chart using the [_bitnami/volsync_ container](https://github.com/bitnami/containers/tree/main/bitnami/volsync).

We apologize for the inconvenience. We will be sure to reconsider it in the future.
