### ISSUE TITLE
Add support for Apache Airflow Deferrable Operators

### ISSUE THREAD

**Issue by michal-cech** [bitnami/containers#7252]
### Name and Version

bitnami/airflow-triggerer:0.0.1

### What is the problem this feature will solve?

Apache Airflow supports the concept of _Deferrable operators and triggers_ since the 2.2 version. To use this concept, it is necessary to have another container running _triggerer_ process. https://airflow.apache.org/docs/apache-airflow/stable/concepts/deferring.html

### What is the feature you are proposing to solve the problem?

I propose releasing a new container and helm chart to support this concept.

**Comment by carrodher** [comment]
Thanks for the suggestion, we already have an ongoing issue (https://github.com/bitnami/charts/issues/8462) and an associated internal task for this topic, please refer to that one in order to have a single place for communicating the progress.
At this moment the internal task is still on our backlog, we will publish any update in that thread.
