### ISSUE TITLE
[Redis-exporter] CVE found in bitnami/redis-exporter:1.50.0-debian-11-r13

### ISSUE THREAD

**Issue by ns-pmistry** [bitnami/containers#74009]
### Name and Version

bitnami/redis-exporter:1.50.0-debian-11-r13

### What architecture are you using?

None

### What steps will reproduce the bug?

setup jfrog scan for docker
run jf docker scan <<image_name>>:<>
I'm attaching the result below
[redis-exporter-1.50.0-debian-11-r13-CVE-report.txt](https://github.com/user-attachments/files/17542887/redis-exporter-1.50.0-debian-11-r13-CVE-report.txt)

These issues are blocking us to deploy in fedramp environment

### What do you see instead?

CVE report attached

**Comment by carrodher** [comment]
I understand your concern about security vulnerabilities. We regularly update our images with the latest system packages; however, certain CVEs may persist until they are patched in the OS or application. Additionally, some CVEs remain unfixed due to the absence of available patches. In vulnerability scanners like Trivy, you can use the `--ignore-unfixed` flag to ignore such CVEs. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

The Bitnami Application Catalog (OpenSource) is built on Debian 12. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 11 & 12, PhotonOS 5, Ubuntu 22.04 & 24.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

For instance, in this case, there is no fixable vulnerability when using the latest image:
```console
$ trivy image bitnami/redis-exporter:latest --scanners vuln --ignore-unfixed
2024-10-28T17:19:33+01:00	INFO	[vuln] Vulnerability scanning is enabled
2024-10-28T17:19:40+01:00	INFO	Detected OS	family="debian" version="12.7"
2024-10-28T17:19:40+01:00	INFO	[debian] Detecting vulnerabilities...	os_version="12" pkg_num=100
2024-10-28T17:19:40+01:00	INFO	Number of language-specific files	num=3
2024-10-28T17:19:40+01:00	INFO	[gobinary] Detecting vulnerabilities...
2024-10-28T17:19:40+01:00	INFO	[bitnami] Detecting vulnerabilities...
2024-10-28T17:19:40+01:00	WARN	Using severities from other vendors for some vulnerabilities. Read https://aquasecurity.github.io/trivy/v0.56/docs/scanner/vulnerability#severity-selection for details.

bitnami/redis-exporter (debian 12.7)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
