### ISSUE TITLE
[bitnami/oras] - Debian tagged image doesn't have minideb as might be expected

### ISSUE THREAD

**Issue by EdKingscote** [bitnami/containers#74098]
### Name and Version

bitnami/oras:1-debian-12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`docker run -it --entrypoint="" bitnami/oras:1-debian-12 /bin/bash`
OR
`docker run -it --entrypoint="" bitnami/oras:1-debian-12 /bin/sh`

### What is the expected behavior?

`root@8c72884ff519:/#`
OR
`#`

### What do you see instead?

```
Unable to find image 'bitnami/oras:1-debian-12' locally
1-debian-12: Pulling from bitnami/oras
Digest: sha256:efd73d06d907f5efd1ba4eddd00aff67b6e22590366d19a7dc5de3b3ab6da9ad
Status: Downloaded newer image for bitnami/oras:1-debian-12
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown.
ERRO[0001] error waiting for container:
```
OR
```
docker run -it --entrypoint="" registry.ops.canarie.ca/pullthru/bitnami/oras:1-debian-12 /bin/sh
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown.
ERRO[0000] error waiting for container:
```

### Additional information

I'm trying to use the oras container as part of a gitlab pipeline to update OCI artifacts, so I need a bash shell - reference: 
https://docs.gitlab.com/runner/shells/index.html#shell-profile-loading

I was expecting the debian tagged variants of this image to be built from minideb rather than scratch.

**Comment by carrodher** [comment]
Apologies for the tag confusion. As you've correctly noted, the bitnami/oras container lacks a bash shell because it is built as a scratch/distroless container. Although it uses minideb as the builder (see [Dockerfile Line 4](https://github.com/bitnami/containers/blob/main/bitnami/oras/1/debian-12/Dockerfile#L4)), it is ultimately constructed as a scratch container due to its simplicity (see [Dockerfile Line 32](https://github.com/bitnami/containers/blob/main/bitnami/oras/1/debian-12/Dockerfile#L32)).

Using scratch or distroless containers offers significant advantages, such as minimized image size, which reduces the surface area for vulnerabilities and enhances security. These lean images also improve performance by limiting the container to only essential components, making them a reliable choice for production environments.
