### ISSUE TITLE
Notice about LTS branches and pull rates in Docker Hub

### ISSUE THREAD

**Issue by carrodher** [bitnami/containers#75671]
Starting December 10th, 2024, only the latest stable branch of applications deployed by Bitnami Helm charts will receive updates in the free Bitnami catalog. Previous versions already released will not be deleted. They are still available to pull from DockerHub.
For example, for PostgreSQL, only branch 17 (the latest stable version) will be maintained in the free catalog. Other upstream-supported branches, such as 13, 14, 15, and 16, will be exclusively available through Bitnami Premium.

Also on that date, all free Bitnami Helm charts and containers will be subject to standard pull-rate limits and pull caps in Docker Hub.

To continue accessing up-to-date releases of all the upstream-supported branches and to pull without any limitations, you can upgrade to Bitnami Premium. Please check the Bitnami Premium page in our partner Arrow's marketplace. See [https://www.arrow.com/globalecs/na/vendors/bitnami](https://www.arrow.com/globalecs/na/vendors/bitnami?utm_source=GitHub&utm_medium=containers) for more information.

**Comment by gusfcarvalho** [comment]
Out of curiosity, Was this something imposed by docker.io agreements, or was it a business decision from VMware/broadcom?

is there anywhere where the rationale behind it is available?

**Comment by thesuperzapper** [comment]
I would like to __urgently__ request Bitnami/VMWare (@maarc, @ridruejo, @carrodher) work with Docker (@justincormack, @girisreenivas) to keep the no-rate-limits on a few critical images so Kubernetes clusters don't break a few days before Christmas all over the world (and with only 3 days notice).

Specifically, the Bitnami images which contain clients like `kubectl`, `bash`, `mysql` are used by countless open-source project and enterprises because they don't have pull limits. Suddenly introducing limits will break many important things like CronJobs and other scripts, because they are pulled more frequently than other images.

Please reconsider adding the rate-limits on the following critical images, at least till after the holidays:

- [`docker.io/bitnami/kubectl`](https://hub.docker.com/r/bitnami/kubectl)
- [`docker.io/bitnami/os-shell`](https://hub.docker.com/r/bitnami/os-shell)
- [`docker.io/bitnami/minio-client`](https://hub.docker.com/r/bitnami/minio-client)
- [`docker.io/bitnami/azure-cli`](https://hub.docker.com/r/bitnami/azure-cli)
- [`docker.io/bitnami/postgresql`](https://hub.docker.com/r/bitnami/postgresql)
- [`docker.io/bitnami/mysql`](https://hub.docker.com/r/bitnami/mysql)
- [`docker.io/bitnami/redis`](https://hub.docker.com/r/bitnami/redis)

__But if you only do one, please do `docker.io/bitnami/kubectl` as that one will cause sooo many problems, as it's effectively the standard `kubectl` image.__

**Comment by d-lebed** [comment]
I didn't ask for this for Christmas.

**Comment by tuananh** [comment]
while I can understand the decision, doing this with such short notice and right before Christmas is just sad.

**Comment by jkroepke** [comment]
Keep in mind that if you are using the legacy Helm index (https://charts.bitnami.com/bitnami/index.yaml), your deployments are still subject to standard Docker Hub rate limits because the index also points to Docker Hub.

**Comment by bradmbock** [comment]
Hi, product manager for Bitnami here. We hear you and realize the timing is not ideal. Unfortunately we are obligated to make this change as quickly as possible due to business and partner requirements. However, in an effort to minimize impact on this community we are now implementing a plan to roll out these changes incrementally and not fully implement until you get through the holiday break. 

This morning we have introduced the changes temporarily for three hours to measure the effect. We will then implement a second 12-hour temporary change on Thursday December 19th. Finally, the permanent change will take effect on Monday, January 6th 2025.

Thank you for the feedback. For more context about these changes, and our continued commitment to providing the Bitnami catalog for our community, you can read more in our[ recent blog post](https://blog.bitnami.com/2024/11/bitnami-premium.html).

**Comment by ydixken** [comment]
> Unfortunately we are obligated to make this change as quickly as possible **due to corporate greed.** 

There, I fixed it for you.

**Comment by max06** [comment]
Time to get rid of bitnami images, I guess. ¯\_(ツ)_/¯

**Comment by gusfcarvalho** [comment]
> Time to get rid of bitnami images, I guess. ¯_(ツ)_/¯
> 
> Edit: I definitely wish you good luck with the upcoming licencing issues!

Why would there be any licensing issues?

**Comment by mamoit** [comment]
Merry christmas everyone!
And a happy on-call duty.

Now seriously, @carrodher can't you delay this decision one month?
Roll it out on the 6th of January or even the 2nd or 3rd (which is a Friday, but still better than this), at least there will be people in the office by then to put out the unexpected fires, it won't have to be the poor people who pulled the short straw and got the christmas/new year's on call duty.

You will save a lot of people a lot of headaches and in return get some kudos for reviewing your decision.

**Comment by mamoit** [comment]
Ok, aparently the decision has been delayed :+1: thank you!
![image](https://github.com/user-attachments/assets/4d4c6f96-3fd2-4fd6-8d18-8c07af87c7d6)
https://blog.bitnami.com/2024/11/bitnami-premium.html
