### ISSUE TITLE
CVE Fix

### ISSUE THREAD

**Issue by AdityaPendyala** [bitnami/containers#75881]
### Name and Version

bitnami/oauth2proxy:7.7.1

### What is the problem this feature will solve?

Greeting,
I had just encountered a CVE on docker scout and Microsoft Defender about 2 weeks ago and just wanted to report the issue. I am aware this is not the right forum to report vulnerabilities and I did go through the steps for raising concerns, but I was unable to contact anyone from the team as I couldn't find the email address, so if anyone could help me out with the maintainers email address I can share the details.

### What is the feature you are proposing to solve the problem?

Fixing Critical CVE

**Comment by carrodher** [comment]
I understand your concern about security vulnerabilities. We regularly update our images with the latest system packages; however, certain CVEs may persist until they are patched in the OS or application. Additionally, some CVEs remain unfixed due to the absence of available patches. In vulnerability scanners like Trivy, you can use the `--ignore-unfixed` flag to ignore such CVEs. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

In this case, those vulnerabilities are within the Go binary itself, see
```console
$ trivy image bitnami/oauth2-proxy:7.7.1 --ignore-unfixed
2024-12-23T16:47:35+01:00	INFO	[vuln] Vulnerability scanning is enabled
2024-12-23T16:47:35+01:00	INFO	[secret] Secret scanning is enabled
2024-12-23T16:47:35+01:00	INFO	[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-12-23T16:47:35+01:00	INFO	[secret] Please see also https://aquasecurity.github.io/trivy/v0.58/docs/scanner/secret#recommendation for faster secret detection
2024-12-23T16:47:56+01:00	INFO	Detected OS	family="debian" version="12.8"
2024-12-23T16:47:56+01:00	INFO	[debian] Detecting vulnerabilities...	os_version="12" pkg_num=100
2024-12-23T16:47:56+01:00	INFO	Number of language-specific files	num=3
2024-12-23T16:47:56+01:00	INFO	[gobinary] Detecting vulnerabilities...
2024-12-23T16:47:56+01:00	INFO	[bitnami] Detecting vulnerabilities...
2024-12-23T16:47:56+01:00	WARN	Using severities from other vendors for some vulnerabilities. Read https://aquasecurity.github.io/trivy/v0.58/docs/scanner/vulnerability#severity-selection for details.

bitnami/oauth2-proxy:7.7.1 (debian 12.8)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

2024-12-23T16:47:56+01:00	INFO	Table result includes only package filenames. Use '--format json' option to get the full path to the package file.

opt/bitnami/oauth2-proxy/bin/oauth2-proxy (gobinary)

Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 1)

┌─────────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬────────────────────────────────────────────────────────┐
│       Library       │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                         Title                          │
├─────────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼────────────────────────────────────────────────────────┤
│ golang.org/x/crypto │ CVE-2024-45337 │ CRITICAL │ fixed  │ v0.27.0           │ 0.31.0        │ golang.org/x/crypto/ssh: Misuse of                     │
│                     │                │          │        │                   │               │ ServerConfig.PublicKeyCallback may cause authorization │
│                     │                │          │        │                   │               │ bypass in golang.org/x/crypto                          │
│                     │                │          │        │                   │               │ https://avd.aquasec.com/nvd/cve-2024-45337             │
├─────────────────────┼────────────────┼──────────┤        ├───────────────────┼───────────────┼────────────────────────────────────────────────────────┤
│ golang.org/x/net    │ CVE-2024-45338 │ HIGH     │        │ v0.29.0           │ 0.33.0        │ golang.org/x/net/html: Non-linear parsing of           │
│                     │                │          │        │                   │               │ case-insensitive content in golang.org/x/net/html      │
│                     │                │          │        │                   │               │ https://avd.aquasec.com/nvd/cve-2024-45338             │
└─────────────────────┴────────────────┴──────────┴────────┴───────────────────┴───────────────┴────────────────────────────────────────────────────────┘

```

The Bitnami Application Catalog (OpenSource) is built on Debian 12. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 11 & 12, PhotonOS 5, Ubuntu 22.04 & 24.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

If you have any further questions, feel free to ask.

**Comment by AdityaPendyala** [comment]
Hey @carrodher!
Thank you for your response, I raised the issue with respect to the critical vulnerability in the golang.org/x/crypto library coming with Go binary. I went through the [repository](https://github.com/oauth2-proxy/oauth2-proxy) mentioned in the docker hub and found that the fix for that has already been merged. This is the pr for reference: https://github.com/oauth2-proxy/oauth2-proxy/pull/2884 . Looking at this I assumed that it might be fixed soon enough, and we would really appreciate it, if it fixed since we've been getting quite a few escalations for having critical vulnerabilities in our application.

**Comment by carrodher** [comment]
As you rightly said, the fix for that CVE was merged in the upstream master branch, but they didn't cut a new release bundling those changes, being 7.7.1 the latest available version at https://github.com/oauth2-proxy/oauth2-proxy/releases.

Once there is a new version there, our automated test & release pipeline will detect it and build the Bitnami container for oauth2-proxy, but if there is not a release upstream there is nothing we can do on our side.

**Comment by AdityaPendyala** [comment]
Ahh I see, no worries! Can we somewhat get any estimate as to when the next release could be?

**Comment by carrodher** [comment]
That's something to ask the upstream maintainers, feel free to open a ticket at https://github.com/oauth2-proxy/oauth2-proxy, probably they can help you

**Comment by AdityaPendyala** [comment]
Ok sure, Thanks a lot!
