### ISSUE TITLE
[bitnami/airflow] Support MySQL Database

### ISSUE THREAD

**Issue by Kim-frau** [bitnami/containers#8939]
### Name and Version

bitnami/airflow 2.3.3

### What is the problem this feature will solve?

We usually use MySQL as database, and would like to use it for airflow as well. Is a support planned on MySQL for Airflow in a near future?

### What is the feature you are proposing to solve the problem?

Add env variables for MySQL support.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but that is not in our roadmap right now.

**Comment by carrodher** [comment]
Hi, unfortunately, and due to other priorities in the team, there are no plans to work on the addition of this feature in the mid-term.

If you would like to contribute by creating a PR, the Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
