### ISSUE TITLE
Read-only root filesystem

### ISSUE THREAD

**Issue by KuroObi** [bitnami/containers#985]
For security considerations the image should be able to run with the docker/kubernetes parameter read-only root file-system and only directories, that need to be written into, mounted as volumes.

At the moment this is not possible and leaves the keycloak container open for attack vectors.

**Steps to reproduce the issue:**

- docker
append `--read-only --volume <volume-name>:/mount/path` to the start command

- docker-compose
add `read_only: true` into the compose file

- kubernetes
Add to statefulset container specs
```yaml
securityContext:
  readOnlyRootFilesystem: true
```

**Comment by carrodher** [comment]
Unfortunately, this suggestion was added a year ago and although there is an internal task to evaluate it, it was not planned as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.
