### ISSUE TITLE
[bitnami/fluentd] Add typhoeus gem

### ISSUE THREAD

**Issue by kvokka** [bitnami/containers#990]
### Name and Version

bitnami/fluentd:latest

### What is the problem this feature will solve?

This is the optional dependency of https://github.com/uken/fluent-plugin-elasticsearch#http_backend 
But it helps to fix this problem https://github.com/uken/fluent-plugin-elasticsearch/issues/453#issuecomment-1046401927

Also, want to mention, that the optional gem `oj` is included in the package, so why not install `typhoeus` gem? (it's pretty small)

### What is the feature you are proposing to solve the problem?

install typhoeus gem

**Comment by carrodher** [comment]
Unfortunately, this suggestion was added a year ago and although there is an internal task to evaluate it, it was not planned as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

I totally agree with you that is weird having the `oj` gem but not others. In the end, this is an objective decision and it will depend on the use case and the different scenarios. The gem that is interesting for you can be irrelevant to another user. That's why we are trying to move (little by little) to a more customizable approach where the assets don't include any customization out of the box but there are methods for users to add the required packages or components.

Being said that, in this case, the decision was to not include `typhoeus` by default in the container image. At this moment there is a workaround to include it (although it is not the best option) and we will work on improving how the container image can be customized.
