### ISSUE TITLE
Error at docker run 

### ISSUE THREAD

**Issue by jehutyy** [bitnami/containers#996]
The following command from README.md :
 ```
docker run --detach --rm --name test-openldap   --network my-network   --env LDAP_ADMIN_USERNAME=admin   --env LDAP_ADMIN_PASSWORD=adminpassword   --env LDAP_USERS=customuser   --env LDAP_PASSWORDS=custompassword   bitnami/openldap:latest
```

triggers this error : 
```
# docker logs -f test-openldap 
 13:48:24.30 INFO  ==> ** Starting LDAP setup **
 13:48:24.36 INFO  ==> Validating settings in LDAP_* env vars
 13:48:24.37 INFO  ==> Initializing OpenLDAP...
 13:48:24.40 INFO  ==> Creating LDAP online configuration
 13:48:24.42 INFO  ==> Starting OpenLDAP server in background
 13:48:43.59 INFO  ==> Configure LDAP credentials for admin user
 13:48:45.05 INFO  ==> Adding LDAP extra schemas
 13:48:45.74 INFO  ==> Creating LDAP default tree
 13:48:46.70 INFO  ==> ** LDAP setup finished! **

 13:48:46.74 INFO  ==> ** Starting slapd **
5ee2363e @(#) $OpenLDAP: slapd 2.4.50 (May  4 2020 16:17:50) $
        @5fb3c780904c:/bitnami/blacksmith-sandox/openldap-2.4.50/servers/slapd
5ee23655 hdb_db_open: database "dc=example,dc=org": database already in use.
5ee23655 backend_startup_one (type=hdb, suffix="dc=example,dc=org"): bi_db_open failed! (-1)
5ee23655 slapd stopped.
```

**Comment by fmulero** [comment]
Hi @harshkolhatkar 

With the command at the beginning of this issue, are you facing the same problem?

```
docker run --detach --rm --name test-openldap    --env LDAP_ADMIN_USERNAME=admin   --env LDAP_ADMIN_PASSWORD=adminpassword   --env LDAP_USERS=customuser   --env LDAP_PASSWORDS=custompassword   bitnami/openldap:latest
```

If that command works, please open a new issue. This is a very old topic and maybe is not related to your issue

**Comment by harshkolhatkar** [comment]
> 

I was actually able to get it working by exposing those ports on localhost. The logs then started populating once I did ldapsearch on my domain. I guess the logs just say slapd is starting but doesn't confirm it has started successfully, that caused me to believe that there was some error. Thanks for your help!

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this year, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
